"use client";

import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { DollarSign, Zap, TrendingUp, Activity, Download, FileText } from "lucide-react";
import { AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from "recharts";
import { toast } from "sonner";

interface UsageMetric {
  model: string;
  totalTokens: number;
  cost: number;
  requests: number;
  avgLatency: number;
  successRate: number;
}

interface SavedReport {
  id: string;
  content: string;
  timestamp: string;
  timeRange: string;
}

const usageData: UsageMetric[] = [
  {
    model: "GPT-4 Turbo",
    totalTokens: 12450000,
    cost: 124.50,
    requests: 3421,
    avgLatency: 1850,
    successRate: 99.2
  },
  {
    model: "Claude 3.5 Sonnet",
    totalTokens: 8920000,
    cost: 26.76,
    requests: 2156,
    avgLatency: 1420,
    successRate: 99.8
  },
  {
    model: "Mistral Large",
    totalTokens: 5670000,
    cost: 22.68,
    requests: 1834,
    avgLatency: 1680,
    successRate: 98.5
  },
  {
    model: "Llama 3.1 70B",
    totalTokens: 3240000,
    cost: 0.00,
    requests: 892,
    avgLatency: 2840,
    successRate: 97.8
  }
];

const dailyUsage = [
  { date: "Mon", tokens: 2.1, cost: 21.5 },
  { date: "Tue", tokens: 2.8, cost: 28.2 },
  { date: "Wed", tokens: 3.2, cost: 32.4 },
  { date: "Thu", tokens: 2.9, cost: 29.1 },
  { date: "Fri", tokens: 3.5, cost: 35.8 },
  { date: "Sat", tokens: 1.8, cost: 18.3 },
  { date: "Sun", tokens: 1.5, cost: 15.2 }
];

const operationBreakdown = [
  { name: "Document Analysis", value: 45, cost: 89.5 },
  { name: "Chat Queries", value: 28, cost: 34.2 },
  { name: "Translation", value: 15, cost: 18.7 },
  { name: "Summarization", value: 12, cost: 12.1 }
];

const COLORS = ['#3b82f6', '#8b5cf6', '#ec4899', '#f59e0b'];

export const LLMUsageMonitorPanel = () => {
  const [timeRange, setTimeRange] = useState<"day" | "week" | "month">("week");
  const [savedReports, setSavedReports] = useState<SavedReport[]>([]);

  // Load saved reports from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem("llm_usage_reports");
    if (stored) {
      try {
        setSavedReports(JSON.parse(stored));
      } catch (e) {
        console.error("Error loading saved reports:", e);
      }
    }
  }, []);

  const totalCost = usageData.reduce((sum, m) => sum + m.cost, 0);
  const totalTokens = usageData.reduce((sum, m) => sum + m.totalTokens, 0);
  const totalRequests = usageData.reduce((sum, m) => sum + m.requests, 0);
  const avgLatency = usageData.reduce((sum, m) => sum + m.avgLatency, 0) / usageData.length;

  const downloadReport = () => {
    const report = `# LLM Usage & Cost Analytics Report
    
## Summary
Period: Last ${timeRange}
Total Cost: $${totalCost.toFixed(2)}
Total Tokens: ${(totalTokens / 1000000).toFixed(2)}M
Total Requests: ${totalRequests.toLocaleString()}
Average Latency: ${avgLatency.toFixed(0)}ms

## By Model
${usageData.map(m => `
### ${m.model}
- Tokens: ${(m.totalTokens / 1000000).toFixed(2)}M
- Cost: $${m.cost.toFixed(2)}
- Requests: ${m.requests.toLocaleString()}
- Avg Latency: ${m.avgLatency}ms
- Success Rate: ${m.successRate}%
`).join('')}

## By Operation
${operationBreakdown.map(op => `
- ${op.name}: ${op.value}% of usage ($${op.cost.toFixed(2)})
`).join('')}

---
Generated by FinSight X LLM Usage Monitor
`;

    // Save to localStorage
    const savedReport: SavedReport = {
      id: `llm_report_${Date.now()}`,
      content: report,
      timestamp: new Date().toISOString(),
      timeRange: timeRange
    };

    const updatedReports = [savedReport, ...savedReports].slice(0, 20); // Keep last 20 reports
    setSavedReports(updatedReports);
    localStorage.setItem("llm_usage_reports", JSON.stringify(updatedReports));

    // Trigger file download
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LLM_Usage_Report_${timeRange}_${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Report downloaded and saved to history!");
  };

  const downloadSavedReport = (report: SavedReport) => {
    const blob = new Blob([report.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LLM_Usage_Report_${report.timeRange}_${report.timestamp.split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Report re-downloaded!");
  };

  return (
    <div className="space-y-6">
      <Card className="border-yellow-200 dark:border-yellow-800 bg-gradient-to-br from-white to-yellow-50 dark:from-slate-900 dark:to-yellow-950">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Activity className="h-6 w-6 text-yellow-600 dark:text-yellow-400" />
                LLM Usage Monitor & Cost Analytics
              </CardTitle>
              <CardDescription>
                Track token usage, API latency, and cost governance
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <div className="flex gap-1">
                {(["day", "week", "month"] as const).map((range) => (
                  <Button
                    key={range}
                    variant={timeRange === range ? "default" : "outline"}
                    size="sm"
                    onClick={() => setTimeRange(range)}
                  >
                    {range.charAt(0).toUpperCase() + range.slice(1)}
                  </Button>
                ))}
              </div>
              <Button variant="outline" onClick={downloadReport} className="gap-2">
                <Download className="h-4 w-4" />
                Export Report
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Key Metrics */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <Card className="bg-gradient-to-br from-green-50 to-emerald-50 dark:from-green-950 dark:to-emerald-950">
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-2xl font-bold text-green-700 dark:text-green-400">
                      ${totalCost.toFixed(2)}
                    </div>
                    <div className="text-sm text-green-600 dark:text-green-500">Total Cost</div>
                  </div>
                  <DollarSign className="h-8 w-8 text-green-600 dark:text-green-400 opacity-50" />
                </div>
              </CardContent>
            </Card>
            <Card className="bg-gradient-to-br from-blue-50 to-cyan-50 dark:from-blue-950 dark:to-cyan-950">
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-2xl font-bold text-blue-700 dark:text-blue-400">
                      {(totalTokens / 1000000).toFixed(1)}M
                    </div>
                    <div className="text-sm text-blue-600 dark:text-blue-500">Total Tokens</div>
                  </div>
                  <Zap className="h-8 w-8 text-blue-600 dark:text-blue-400 opacity-50" />
                </div>
              </CardContent>
            </Card>
            <Card className="bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-950 dark:to-pink-950">
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-2xl font-bold text-purple-700 dark:text-purple-400">
                      {totalRequests.toLocaleString()}
                    </div>
                    <div className="text-sm text-purple-600 dark:text-purple-500">API Requests</div>
                  </div>
                  <Activity className="h-8 w-8 text-purple-600 dark:text-purple-400 opacity-50" />
                </div>
              </CardContent>
            </Card>
            <Card className="bg-gradient-to-br from-orange-50 to-red-50 dark:from-orange-950 dark:to-red-950">
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-2xl font-bold text-orange-700 dark:text-orange-400">
                      {avgLatency.toFixed(0)}ms
                    </div>
                    <div className="text-sm text-orange-600 dark:text-orange-500">Avg Latency</div>
                  </div>
                  <TrendingUp className="h-8 w-8 text-orange-600 dark:text-orange-400 opacity-50" />
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Usage Over Time */}
          <Card className="bg-white/50 dark:bg-slate-900/50">
            <CardContent className="p-6">
              <h3 className="font-semibold mb-4">Daily Usage & Cost Trend</h3>
              <ResponsiveContainer width="100%" height={300}>
                <AreaChart data={dailyUsage}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="date" />
                  <YAxis yAxisId="left" label={{ value: 'Tokens (M)', angle: -90, position: 'insideLeft' }} />
                  <YAxis yAxisId="right" orientation="right" label={{ value: 'Cost ($)', angle: 90, position: 'insideRight' }} />
                  <Tooltip />
                  <Legend />
                  <Area yAxisId="left" type="monotone" dataKey="tokens" stroke="#3b82f6" fill="#93c5fd" name="Tokens (M)" />
                  <Area yAxisId="right" type="monotone" dataKey="cost" stroke="#10b981" fill="#86efac" name="Cost ($)" />
                </AreaChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Model Comparison */}
            <Card className="bg-white/50 dark:bg-slate-900/50">
              <CardContent className="p-6">
                <h3 className="font-semibold mb-4">Cost by Model</h3>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={usageData}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="model" angle={-45} textAnchor="end" height={100} />
                    <YAxis />
                    <Tooltip />
                    <Bar dataKey="cost" fill="#3b82f6" name="Cost ($)" />
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {/* Operation Breakdown */}
            <Card className="bg-white/50 dark:bg-slate-900/50">
              <CardContent className="p-6">
                <h3 className="font-semibold mb-4">Usage by Operation</h3>
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie
                      data={operationBreakdown}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={({ name, value }) => `${name}: ${value}%`}
                      outerRadius={80}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {operationBreakdown.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>

          {/* Model Details Table */}
          <Card className="bg-white/50 dark:bg-slate-900/50">
            <CardContent className="p-6">
              <h3 className="font-semibold mb-4">Model Performance Details</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b">
                      <th className="text-left p-2">Model</th>
                      <th className="text-right p-2">Tokens</th>
                      <th className="text-right p-2">Cost</th>
                      <th className="text-right p-2">Requests</th>
                      <th className="text-right p-2">Avg Latency</th>
                      <th className="text-right p-2">Success Rate</th>
                    </tr>
                  </thead>
                  <tbody>
                    {usageData.map((model, i) => (
                      <tr key={i} className="border-b">
                        <td className="p-2 font-medium">{model.model}</td>
                        <td className="text-right p-2">{(model.totalTokens / 1000000).toFixed(2)}M</td>
                        <td className="text-right p-2">${model.cost.toFixed(2)}</td>
                        <td className="text-right p-2">{model.requests.toLocaleString()}</td>
                        <td className="text-right p-2">{model.avgLatency}ms</td>
                        <td className="text-right p-2">
                          <Badge variant={model.successRate >= 99 ? "default" : "secondary"}>
                            {model.successRate}%
                          </Badge>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>

          {/* Cost Optimization Tips */}
          <Card className="bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-950 dark:to-indigo-950">
            <CardContent className="p-6">
              <h4 className="font-semibold mb-3">💰 Cost Optimization Recommendations</h4>
              <div className="space-y-2 text-sm text-gray-700 dark:text-gray-300">
                <p>• Consider using Llama 3.1 70B (self-hosted) for non-critical operations - $0 cost</p>
                <p>• Claude 3.5 Sonnet offers best cost/performance ratio for financial analysis</p>
                <p>• Implement response caching to reduce duplicate API calls by 30-40%</p>
                <p>• Use streaming for long responses to improve perceived latency</p>
                <p>• Set up monthly budget alerts to prevent cost overruns</p>
                <p>• Current projected monthly cost: ${(totalCost * 4.33).toFixed(2)}</p>
              </div>
            </CardContent>
          </Card>
        </CardContent>
      </Card>

      {/* Download History */}
      {savedReports.length > 0 && (
        <Card className="border-indigo-200 dark:border-indigo-800">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-indigo-600 dark:text-indigo-400" />
              Download History
            </CardTitle>
            <CardDescription>
              Recently generated reports saved to your browser
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {savedReports.map((report) => (
                <Card key={report.id} className="bg-white/50 dark:bg-slate-900/50">
                  <CardContent className="p-4 flex items-center justify-between">
                    <div>
                      <h4 className="font-medium text-sm">LLM Usage Report ({report.timeRange})</h4>
                      <p className="text-xs text-gray-500">
                        {new Date(report.timestamp).toLocaleString()}
                      </p>
                    </div>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => downloadSavedReport(report)}
                      className="gap-2"
                    >
                      <Download className="h-3 w-3" />
                      Re-download
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
};