import { db } from '@/db';
import { aiAgentLogs } from '@/db/schema';

async function main() {
    const sampleLogs = [
        {
            agentName: 'Parser Agent',
            documentId: 1,
            taskType: 'PDF text extraction',
            status: 'completed',
            processingTimeMs: 2340,
            resultSummary: 'Extracted 47 pages, 12,453 words',
            createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Parser Agent',
            documentId: 5,
            taskType: 'Excel sheet parsing',
            status: 'running',
            processingTimeMs: null,
            resultSummary: null,
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Parser Agent',
            documentId: 8,
            taskType: 'PDF text extraction',
            status: 'failed',
            processingTimeMs: 5600,
            resultSummary: 'Error: Corrupted PDF structure',
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Validator Agent',
            documentId: 1,
            taskType: 'Schema validation',
            status: 'completed',
            processingTimeMs: 890,
            resultSummary: 'Validated 235 data points, 3 warnings',
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Validator Agent',
            documentId: 3,
            taskType: 'Data integrity check',
            status: 'completed',
            processingTimeMs: 1120,
            resultSummary: 'All data fields valid',
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Validator Agent',
            documentId: 11,
            taskType: 'Format validation',
            status: 'completed',
            processingTimeMs: 670,
            resultSummary: 'Format compliance verified',
            createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Anomaly Detector Agent',
            documentId: 1,
            taskType: 'Transaction pattern analysis',
            status: 'completed',
            processingTimeMs: 4500,
            resultSummary: 'Detected 8 anomalies in transaction sequences',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Anomaly Detector Agent',
            documentId: 6,
            taskType: 'Expense pattern detection',
            status: 'completed',
            processingTimeMs: 3200,
            resultSummary: '4 unusual expense patterns identified',
            createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Anomaly Detector Agent',
            documentId: 7,
            taskType: 'Trading pattern analysis',
            status: 'completed',
            processingTimeMs: 5800,
            resultSummary: '7 suspicious trading patterns detected',
            createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Anomaly Detector Agent',
            documentId: 3,
            taskType: 'Cash flow anomaly scan',
            status: 'completed',
            processingTimeMs: 2900,
            resultSummary: 'No anomalies detected',
            createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Fraud Pattern Agent',
            documentId: 1,
            taskType: 'Fraud signature matching',
            status: 'completed',
            processingTimeMs: 6700,
            resultSummary: 'Matched 3 known fraud patterns',
            createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Fraud Pattern Agent',
            documentId: 7,
            taskType: 'Collusion detection',
            status: 'completed',
            processingTimeMs: 8200,
            resultSummary: 'Potential collusion identified between 2 entities',
            createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Fraud Pattern Agent',
            documentId: 11,
            taskType: 'Financial manipulation scan',
            status: 'completed',
            processingTimeMs: 7100,
            resultSummary: 'Revenue manipulation indicators found',
            createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Fraud Pattern Agent',
            documentId: 4,
            taskType: 'Payment fraud check',
            status: 'completed',
            processingTimeMs: 3400,
            resultSummary: 'No fraud indicators detected',
            createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Compliance Agent',
            documentId: 1,
            taskType: 'IFRS compliance verification',
            status: 'completed',
            processingTimeMs: 4800,
            resultSummary: '2 IFRS violations identified',
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Compliance Agent',
            documentId: 11,
            taskType: 'SOX 404 assessment',
            status: 'completed',
            processingTimeMs: 9200,
            resultSummary: 'Material weakness in internal controls',
            createdAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Compliance Agent',
            documentId: 9,
            taskType: 'SEBI regulation check',
            status: 'completed',
            processingTimeMs: 5600,
            resultSummary: 'All SEBI requirements satisfied',
            createdAt: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            agentName: 'Compliance Agent',
            documentId: 2,
            taskType: 'ESG compliance scan',
            status: 'completed',
            processingTimeMs: 6300,
            resultSummary: 'ESG reporting standards met',
            createdAt: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(aiAgentLogs).values(sampleLogs);
    
    console.log('✅ AI Agent Logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});