import { db } from '@/db';
import { alerts } from '@/db/schema';

async function main() {
    const now = new Date();
    const getRandomDateWithinLast30Days = () => {
        const daysAgo = Math.floor(Math.random() * 30);
        const date = new Date(now);
        date.setDate(date.getDate() - daysAgo);
        return date.toISOString();
    };

    const getAcknowledgedDate = (triggeredDate: string) => {
        const triggered = new Date(triggeredDate);
        const daysAfter = Math.floor(Math.random() * 8) + 2; // 2-10 days
        const acknowledged = new Date(triggered);
        acknowledged.setDate(acknowledged.getDate() + daysAfter);
        return acknowledged.toISOString();
    };

    const getResolvedDate = (acknowledgedDate: string) => {
        const acknowledged = new Date(acknowledgedDate);
        const daysAfter = Math.floor(Math.random() * 14) + 1; // 1-15 days
        const resolved = new Date(acknowledged);
        resolved.setDate(resolved.getDate() + daysAfter);
        return resolved.toISOString();
    };

    const getRandomDocumentId = () => Math.floor(Math.random() * 90) + 1;

    const sampleAlerts = [
        // ANOMALY ALERTS (30 total)
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Unusual Revenue Spike Detected - Q4 2024',
            description: 'Revenue increased by 45% compared to Q3 2024, significantly above historical quarterly growth rates. This deviation suggests potential revenue recognition timing issues or one-time transactions. Recommend reviewing revenue contracts and supporting documentation for period-end transactions.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Unexpected Cash Flow Pattern in Operating Activities',
            description: 'Cash flow from operations shows unusual volatility with a 30% variance from forecasted levels. Working capital changes do not align with revenue trends, indicating potential timing differences or collection issues. Detailed cash flow reconciliation is recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Abnormal Inventory Turnover Ratio',
            description: 'Inventory turnover ratio decreased from 6.2 to 4.1, indicating slower inventory movement or potential obsolescence concerns. This trend may signal overstocking or declining product demand. Inventory aging analysis and write-down assessment should be performed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Irregular Asset Depreciation Schedule',
            description: 'Depreciation expense decreased by 25% despite capital expenditure increases, suggesting potential changes in useful life estimates or depreciation methods. This inconsistency requires review of asset capitalization policies and depreciation calculations. Verify compliance with accounting standards.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Unusual End-of-Quarter Transaction Volume',
            description: 'Transaction volume spiked by 60% in the final week of the quarter, with concentrated activity in the last two business days. This pattern raises concerns about potential channel stuffing or aggressive revenue recognition practices. Detailed transaction review and customer acceptance verification recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Unexpected Write-off Pattern Detected',
            description: 'Bad debt write-offs increased by 150% compared to the same period last year, significantly exceeding the allowance for doubtful accounts. This trend suggests potential credit policy changes or deteriorating customer creditworthiness. Review credit approval processes and collection procedures.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Abnormal Accounts Receivable Aging',
            description: 'Accounts receivable aging shows 40% of balances over 90 days past due, up from 15% in the prior quarter. This deterioration indicates collection challenges or potential revenue recognition issues. Immediate attention to collection efforts and customer payment patterns required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Irregular Expense Recognition Pattern',
            description: 'Operating expenses decreased by 20% quarter-over-quarter despite flat revenue, suggesting potential expense capitalization or deferral. This timing mismatch requires investigation into expense classification and period allocation. Verify proper matching principle application.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Unusual Goodwill Valuation Change',
            description: 'Goodwill balance increased by $15M without corresponding acquisitions, indicating potential purchase price allocation adjustments or valuation model changes. This requires detailed review of acquisition accounting and impairment testing methodology. Ensure compliance with ASC 350 requirements.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Unexpected Derivative Position Changes',
            description: 'Derivative liability valuation shifted from $2M liability to $1.5M asset within the quarter, showing unusual volatility inconsistent with underlying exposures. This change suggests potential marking-to-market issues or hedge effectiveness concerns. Review derivative valuation models and hedge documentation.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Abnormal Reserve Adjustments',
            description: 'Warranty reserve decreased by 35% despite increased product sales and historical claim rates remaining stable. This reduction appears inconsistent with business trends and may indicate under-reserving. Detailed actuarial analysis and claim history review recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Irregular Intercompany Transaction Pattern',
            description: 'Intercompany transactions increased by 80% with significant concentration in management fee allocations and transfer pricing adjustments. This pattern requires review to ensure proper elimination and arm\'s length pricing. Verify compliance with transfer pricing documentation requirements.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'low',
            title: 'Unusual Tax Rate Fluctuation',
            description: 'Effective tax rate decreased from 24% to 16% without disclosed tax planning strategies or jurisdiction changes. This variance suggests potential deferred tax calculation errors or unrecorded tax positions. Review tax provision calculations and uncertain tax position assessments.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Unexpected Margin Compression Pattern',
            description: 'Gross margin declined by 8 percentage points to 32% while cost of goods sold per unit remained stable, indicating potential pricing pressure or product mix shifts. This trend requires analysis of pricing strategies, competitive dynamics, and cost structure changes.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Abnormal Working Capital Changes',
            description: 'Working capital decreased by $25M driven by simultaneous increases in payables and decreases in receivables, creating unusual timing patterns. This shift may indicate aggressive payment terms negotiations or collection acceleration tactics. Detailed working capital component analysis required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Irregular Prepaid Expense Balance',
            description: 'Prepaid expenses increased by 120% without corresponding operational changes or new contracts. This significant increase suggests potential expense deferral or incorrect period allocation. Review prepaid amortization schedules and expense recognition policies.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Unusual Accrued Liability Reversal',
            description: 'Accrued liabilities decreased by $8M with reversals concentrated in restructuring and litigation reserves. This pattern suggests potential reserve release timing manipulation or overly aggressive reserve reduction. Detailed review of accrual calculations and supporting documentation needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Abnormal Stock Compensation Expense',
            description: 'Stock-based compensation decreased by 40% despite new equity grants and stable employee count. This reduction appears inconsistent with grant activity and may indicate incorrect valuation or vesting schedule calculations. Review equity grant documentation and fair value calculations.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'low',
            title: 'Irregular Foreign Exchange Impact',
            description: 'Foreign currency translation adjustment showed $3M gain despite unfavorable exchange rate movements in key operating currencies. This inconsistency suggests potential translation methodology errors or incomplete hedge documentation. Review currency translation calculations and hedging strategy.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Unexpected Customer Concentration Change',
            description: 'Top customer revenue concentration increased from 15% to 35% of total revenue within a single quarter, creating significant dependency risk. This rapid concentration change requires assessment of customer relationship stability and contract terms. Consider disclosure implications.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Abnormal Related Party Balance Growth',
            description: 'Related party receivables increased by $10M representing 25% of total receivables, significantly above historical levels. This concentration raises concerns about transaction terms and collectibility. Detailed related party transaction review and disclosure assessment required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Irregular Deferred Revenue Pattern',
            description: 'Deferred revenue decreased by 30% while new bookings remained stable, suggesting accelerated revenue recognition or non-standard contract terms. This trend requires review of revenue recognition policies and customer contract analysis. Verify ASC 606 compliance.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'low',
            title: 'Unusual Employee Benefit Cost Variance',
            description: 'Employee benefit costs declined by 15% despite stable headcount and no disclosed plan changes. This reduction suggests potential actuarial assumption changes or incorrect benefit accrual calculations. Review pension and postretirement benefit calculations.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Abnormal Capitalized Software Development',
            description: 'Capitalized software development costs increased by 200% while R&D headcount remained flat, suggesting potential over-capitalization or incorrect expense classification. This requires detailed review of capitalization criteria and project-level documentation. Ensure ASC 985-20 compliance.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Irregular Lease Liability Balance',
            description: 'Operating lease liabilities decreased by $12M without corresponding lease terminations or modifications disclosed. This variance suggests potential lease accounting errors or incomplete lease population. Review lease accounting under ASC 842 and verify completeness of lease inventory.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Unexpected Contingency Reserve Release',
            description: 'Legal contingency reserves decreased by $5M without disclosed settlements or case resolutions. This timing raises questions about reserve adequacy and litigation outcome assessments. Detailed review of legal matters and consultation with legal counsel recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Abnormal Intangible Asset Amortization',
            description: 'Intangible asset amortization expense decreased by 35% despite stable intangible asset balances, suggesting potential useful life extension or amortization calculation errors. This requires review of intangible asset amortization schedules and impairment testing. Verify consistency with acquisition accounting.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'low',
            title: 'Irregular Marketing Expense Pattern',
            description: 'Marketing expenses dropped by 50% in the final month of the quarter despite no disclosed budget changes or campaign timing shifts. This pattern suggests potential expense deferral or capitalization issues. Review marketing expense recognition and allocation policies.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'medium',
            title: 'Unusual Compensation Accrual Adjustment',
            description: 'Bonus accrual reversed by $4M in final quarter despite performance metrics indicating payout expectations. This reversal appears inconsistent with compensation plan terms and performance outcomes. Review bonus calculation methodology and management performance assessments.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'anomaly',
            severity: 'high',
            title: 'Abnormal Investment Portfolio Valuation',
            description: 'Investment portfolio marked up by $7M despite declining market valuations in comparable securities. This valuation inconsistency suggests potential marking-to-market issues or Level 3 fair value measurement concerns. Detailed investment valuation review and external pricing source verification required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },

        // THRESHOLD BREACH ALERTS (25 total)
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'critical',
            title: 'Debt-to-Equity Ratio Exceeds Risk Threshold (2.5)',
            description: 'Current debt-to-equity ratio of 2.7 exceeds the maximum acceptable threshold of 2.5, indicating elevated financial leverage and potential covenant breach risk. This deterioration impacts borrowing capacity and credit ratings. Immediate deleveraging strategy and lender communication recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Current Ratio Below Minimum Threshold (0.9)',
            description: 'Current ratio declined to 0.85, falling below the minimum acceptable level of 0.9, signaling potential short-term liquidity concerns. This breach indicates challenges in meeting near-term obligations and may trigger accelerated payment terms with vendors. Working capital improvement plan required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'medium',
            title: 'ROE Declined Below Industry Average (8%)',
            description: 'Return on equity decreased to 6.5%, falling below the industry benchmark of 8%. This underperformance suggests profitability challenges or capital inefficiency relative to peers. Strategic review of capital allocation and operational efficiency initiatives recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Quick Ratio Warning - Liquidity Concern (0.7)',
            description: 'Quick ratio dropped to 0.65, significantly below the safety threshold of 0.7, indicating immediate liquidity stress excluding inventory conversion. This signals potential cash flow challenges in meeting current liabilities. Enhanced cash flow monitoring and receivables acceleration needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'critical',
            title: 'Interest Coverage Ratio Below Safe Level (2.0)',
            description: 'Interest coverage ratio deteriorated to 1.6, falling below the minimum safe level of 2.0 times, raising debt servicing capability concerns. This breach increases refinancing risk and may trigger credit rating downgrades. Immediate review of debt structure and refinancing options required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Operating Margin Dropped Below 10% Threshold',
            description: 'Operating margin declined to 8.5%, breaching the target minimum of 10%. This compression indicates pressure on core business profitability and operational efficiency. Cost structure review and pricing strategy assessment recommended to restore margin targets.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'medium',
            title: 'Cash Conversion Cycle Exceeds 90 Days',
            description: 'Cash conversion cycle extended to 95 days, exceeding the efficiency target of 90 days. This deterioration ties up working capital and reduces cash generation efficiency. Focus on receivables collection, inventory management, and payables optimization required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'medium',
            title: 'EBITDA Margin Below Target (15%)',
            description: 'EBITDA margin compressed to 13%, falling short of the target threshold of 15%. This underperformance suggests operational leverage challenges or cost structure inefficiencies. Detailed cost analysis and margin improvement initiatives should be prioritized.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Days Sales Outstanding Exceeds 60 Days',
            description: 'Days sales outstanding increased to 68 days, exceeding the acceptable threshold of 60 days, indicating collection efficiency deterioration. This trend negatively impacts cash flow and working capital. Enhanced collection procedures and customer credit review recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'medium',
            title: 'Inventory Days Above Industry Norm (75 days)',
            description: 'Inventory days increased to 82 days, surpassing the industry benchmark of 75 days. This excess suggests potential overstocking, slower turnover, or obsolescence concerns. Inventory optimization and demand planning review needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'critical',
            title: 'Leverage Ratio Exceeds Covenant Limit',
            description: 'Net leverage ratio of 4.2x exceeds the debt covenant maximum of 4.0x, representing a formal covenant breach. This violation may trigger technical default provisions and accelerated payment requirements. Immediate lender notification and waiver negotiation critical.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Working Capital Deficit Detected',
            description: 'Working capital turned negative at -$2.3M, crossing into deficit territory and indicating severe short-term financial stress. This critical condition threatens operational continuity and vendor relationships. Emergency liquidity plan and stakeholder communication essential.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'low',
            title: 'Asset Turnover Below Benchmark (0.8)',
            description: 'Asset turnover ratio of 0.7 falls below the efficiency benchmark of 0.8, indicating underutilization of asset base. This suggests potential for improved capital efficiency or asset rationalization. Strategic review of asset productivity and capital allocation warranted.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Gross Margin Erosion Exceeds 5% YoY',
            description: 'Gross margin declined by 6.5 percentage points year-over-year, exceeding the alert threshold of 5%. This significant erosion indicates pricing pressure, cost inflation, or unfavorable product mix shifts. Immediate pricing and cost management actions required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'critical',
            title: 'Free Cash Flow Turned Negative',
            description: 'Free cash flow of -$5.2M represents a critical breach of the positive cash generation requirement. This negative cash generation threatens financial flexibility and investment capacity. Comprehensive cash flow improvement plan and capital expenditure review urgently needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Accounts Payable Days Exceeds 75',
            description: 'Days payable outstanding increased to 82 days, exceeding the sustainable threshold of 75 days. This extension may indicate cash flow stress or risk of vendor relationship damage. Balance between cash preservation and supplier relationship management required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'medium',
            title: 'R&D to Sales Ratio Below Industry Standard',
            description: 'R&D spending at 4% of revenue falls below the industry benchmark of 6%, potentially compromising long-term competitiveness. This underinvestment may impact innovation pipeline and market position. Strategic review of R&D allocation and competitive positioning recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'low',
            title: 'Capital Expenditure Below Maintenance Level',
            description: 'Capital expenditure at 3% of revenue falls below the minimum maintenance requirement of 4%, suggesting potential underinvestment in asset base. This may lead to future capacity constraints or asset deterioration. Multi-year capex planning review recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Employee Turnover Exceeds 20% Threshold',
            description: 'Annual employee turnover rate of 24% exceeds the acceptable threshold of 20%, indicating retention challenges and increased human capital costs. This trend impacts operational continuity and institutional knowledge. Compensation review and retention strategy development needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'medium',
            title: 'Revenue Growth Below Target (10%)',
            description: 'Year-over-year revenue growth of 7% falls short of the strategic target of 10%, indicating slower market penetration or competitive pressures. This underperformance may impact valuation and growth investment capacity. Sales strategy review and market opportunity assessment recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Customer Acquisition Cost Exceeds LTV Ratio',
            description: 'Customer acquisition cost to lifetime value ratio exceeded 0.35, breaching the efficiency threshold of 0.30. This imbalance suggests marketing inefficiency or pricing challenges. Unit economics review and go-to-market strategy optimization required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'medium',
            title: 'Operating Expense Ratio Above 40% Limit',
            description: 'Operating expenses at 43% of revenue exceed the efficiency target of 40%, indicating cost structure challenges. This ratio compression limits profit margin expansion potential. Detailed expense analysis and efficiency improvement initiatives needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'low',
            title: 'Revenue per Employee Below Industry Average',
            description: 'Revenue per employee of $185K falls below the industry benchmark of $200K, suggesting lower labor productivity. This gap indicates potential for workforce optimization or revenue growth acceleration. Productivity analysis and resource allocation review recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'high',
            title: 'Cash Burn Rate Exceeds Budget by 30%',
            description: 'Monthly cash burn rate of $2.6M exceeds budgeted level of $2M by 30%, reducing runway and threatening financial flexibility. This variance requires immediate cost reduction actions and spending prioritization. Enhanced cash flow monitoring and contingency planning essential.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'threshold_breach',
            severity: 'medium',
            title: 'Net Promoter Score Below Acceptable Level',
            description: 'Net Promoter Score of 32 falls below the target threshold of 40, indicating customer satisfaction concerns. This decline may impact retention and growth prospects. Customer feedback analysis and service improvement initiatives recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },

        // COMPLIANCE VIOLATION ALERTS (20 total)
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'critical',
            title: 'IFRS Compliance Violation - Revenue Recognition Timing',
            description: 'Revenue recognition timing does not comply with IFRS 15 requirements for performance obligation satisfaction. Multiple contracts show revenue recognized upon invoice rather than transfer of control. This material departure from standards requires immediate correction and potential restatement assessment.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'Missing Required Disclosure - Related Party Transactions',
            description: 'Related party transaction disclosure is incomplete, lacking required information about transaction terms, outstanding balances, and key management compensation details per IAS 24. This omission represents a material disclosure deficiency requiring immediate remediation and supplemental disclosure consideration.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'critical',
            title: 'GAAP Violation - Asset Valuation Method Inconsistent',
            description: 'Property, plant and equipment valuation method changed from cost model to revaluation model without proper documentation or disclosure as required by IAS 16. This accounting change requires retrospective application and full disclosure. Immediate correction and disclosure amendment necessary.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'SEC Filing Delay - 10-Q Late Submission',
            description: 'Quarterly report filing missed SEC deadline by 3 business days, triggering late filer status and potential enforcement action. This delay violates Securities Exchange Act filing requirements and may impact listing status. Immediate filing and Form NT explanation required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'critical',
            title: 'SOX 404 Material Weakness - Internal Controls',
            description: 'Material weakness identified in internal controls over financial reporting related to revenue recognition process controls. Insufficient segregation of duties and lack of management review controls detected. This deficiency requires immediate remediation plan and disclosure in upcoming filings.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'IFRS 9 Non-Compliance - Expected Credit Loss Model',
            description: 'Expected credit loss allowance calculation does not incorporate forward-looking information as required by IFRS 9. Historical loss rates used without macroeconomic adjustments or probability-weighted scenarios. Immediate model enhancement and recalculation required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'medium',
            title: 'Segment Reporting Disclosure Incomplete',
            description: 'Operating segment disclosure lacks required information about segment assets, capital expenditure, and depreciation per IFRS 8. Entity-wide geographic information also insufficient. Enhanced disclosure preparation and review process implementation recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'Fair Value Measurement Documentation Missing',
            description: 'Level 3 fair value measurement documentation incomplete, lacking required sensitivity analysis and valuation technique descriptions per IFRS 13. Unobservable input assumptions not adequately disclosed. Comprehensive fair value measurement disclosure enhancement required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'Lease Accounting Non-Compliance with ASC 842',
            description: 'Operating lease accounting does not fully comply with ASC 842 requirements. Several leases not recognized on balance sheet and discount rate calculations appear inconsistent. Comprehensive lease population review and remeasurement required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'medium',
            title: 'Management Discussion & Analysis Insufficient',
            description: 'MD&A section lacks required discussion of off-balance sheet arrangements and contractual obligations per SEC requirements. Critical accounting estimates discussion also inadequate. Enhanced MD&A drafting and review process needed for next filing.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'medium',
            title: 'Stock Compensation Disclosure Inadequate',
            description: 'Share-based payment disclosure lacks required information about fair value assumptions, vesting conditions, and modification details per IFRS 2. Insufficient disclosure of share option activity and weighted average exercise prices. Disclosure enhancement required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'Contingent Liability Disclosure Missing',
            description: 'Material contingent liability related to pending litigation not disclosed despite loss probability assessment indicating reasonably possible outcome per IAS 37. This omission represents significant disclosure deficiency. Immediate disclosure addition and legal consultation required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'medium',
            title: 'Foreign Currency Translation Error',
            description: 'Foreign operation translation methodology inconsistent with IAS 21 requirements. Functional currency determination not properly documented and exchange rate selection appears arbitrary. Translation methodology review and correction required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'Pension Liability Calculation Non-Compliant',
            description: 'Defined benefit pension obligation calculation does not comply with IAS 19 requirements. Actuarial assumptions not disclosed and sensitivity analysis missing. Discount rate selection methodology also inadequately documented. Comprehensive pension accounting review required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'medium',
            title: 'Derivative Hedge Accounting Documentation Incomplete',
            description: 'Hedge accounting documentation does not meet IFRS 9 requirements for hedge effectiveness testing and hedge relationship documentation. Several hedging instruments lack contemporaneous designation documentation. Hedge accounting qualification assessment and documentation enhancement needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'Goodwill Impairment Testing Non-Compliant',
            description: 'Goodwill impairment testing methodology does not comply with IAS 36 requirements. Cash-generating unit identification appears inappropriate and value-in-use calculation lacks required discount rate reconciliation. Immediate impairment testing review and potential reassessment required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'medium',
            title: 'Earnings Per Share Calculation Error',
            description: 'Diluted earnings per share calculation contains errors in determining dilutive potential ordinary shares. Treasury stock method application incorrect for stock options. EPS recalculation and disclosure correction required per IAS 33.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'low',
            title: 'Cash Flow Statement Classification Error',
            description: 'Cash flow statement contains classification errors with interest payments shown in financing activities rather than operating activities per IAS 7. Several other misclassifications identified. Cash flow statement restatement and process improvement recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'high',
            title: 'Business Combination Accounting Incomplete',
            description: 'Recent business combination accounting does not comply with IFRS 3. Purchase price allocation incomplete with provisional amounts not finalized within measurement period. Contingent consideration not properly recognized. Immediate purchase accounting completion required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'compliance_violation',
            severity: 'medium',
            title: 'Subsequent Events Disclosure Missing',
            description: 'Material subsequent event not disclosed despite occurrence between balance sheet date and financial statement issuance date per IAS 10. This omission requires immediate disclosure addition and review process enhancement to ensure complete subsequent event evaluation.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },

        // FRAUD PATTERN ALERTS (15 total)
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'critical',
            title: 'Related Party Transaction Pattern Detected',
            description: 'Systematic pattern of transactions with entities sharing common management identified. Transaction volumes increased 300% with limited business justification and pricing appears non-arm\'s length. This pattern exhibits characteristics consistent with asset diversion schemes. Immediate forensic investigation and legal consultation recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'high',
            title: 'Duplicate Invoice Pattern Identified',
            description: 'Multiple instances of identical invoice amounts submitted by different vendors detected. 15 transactions totaling $280K show matching amounts, dates, and descriptions across supposedly independent suppliers. This pattern strongly indicates payment scheme fraud. Detailed transaction review and vendor verification required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'critical',
            title: 'Circular Transaction Flow Detected',
            description: 'Complex transaction pattern identified where funds flow through multiple related entities before returning to originating company. Transaction trail involves 4 intermediary entities with no apparent business purpose. This structure consistent with revenue inflation or money laundering schemes. Immediate investigation and regulatory reporting assessment required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'high',
            title: 'Ghost Vendor Pattern Match',
            description: 'Vendor profile matches characteristics of fictitious vendor schemes: no verifiable physical address, payments to P.O. box, limited transaction history, and sole approval by single employee. Payment volume of $125K over 6 months with minimal supporting documentation. Immediate vendor verification and payment suspension recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'critical',
            title: 'Revenue Manipulation Indicators Found',
            description: 'Multiple red flags indicating potential revenue manipulation: unusual quarter-end sales spikes, high volume of sales with extended payment terms, and significant subsequent period credits. Pattern shows 35% of Q4 revenue concentrated in final 3 days with 20% credit note rate in following quarter. Comprehensive revenue recognition review required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'high',
            title: 'Channel Stuffing Pattern Detected',
            description: 'Distributor inventory levels increased 250% in final quarter with corresponding sales incentive program modifications. Subsequent period product returns elevated at 30% of prior quarter shipments. This pattern consistent with aggressive channel stuffing to inflate revenue. Customer order validation and inventory reconciliation needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'critical',
            title: 'Cookie Jar Reserve Manipulation Suspected',
            description: 'Reserve balance fluctuations show systematic pattern of over-reserving in strong quarters and releasing reserves in weak quarters to smooth earnings. Warranty reserve release of $4.5M lacks supporting claim data justification. This earnings management pattern requires immediate investigation and potential restatement assessment.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'high',
            title: 'Round Number Transaction Pattern',
            description: 'Unusual concentration of transactions in exact round amounts: 42 transactions totaling $2.1M all ending in $000. This pattern statistically anomalous and consistent with fabricated transaction schemes. Detailed invoice and supporting documentation review required for flagged transactions.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'medium',
            title: 'Sequential Invoice Number Gaps Detected',
            description: 'Invoice sequence analysis reveals systematic gaps in numbering with missing invoice numbers corresponding to voided or deleted transactions. 28 missing invoice numbers over 3 months with $340K in void transaction volume. Pattern suggests potential unauthorized transaction deletion or document destruction. System audit log review recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'high',
            title: 'After-Hours Transaction Entry Pattern',
            description: 'Significant volume of journal entries and adjustments posted outside normal business hours by single user. 67 entries totaling $1.8M posted between 10 PM and 3 AM over past quarter. This pattern raises concerns about unauthorized access and potential manipulation. User access review and entry validation required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'critical',
            title: 'Vendor Address Matches Employee Address',
            description: 'Vendor master file analysis reveals vendor address matching employee residential address. Vendor has received $95K in payments over 6 months with single approver. This conflict of interest pattern indicates potential kickback or fictitious vendor scheme. Immediate investigation and payment suspension required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'medium',
            title: 'Unusual Payment Timing Pattern',
            description: 'Vendor payment pattern shows systematic early payment significantly before due dates with corresponding discounts not properly documented. 23 payments totaling $450K paid average of 15 days early. This pattern may indicate unauthorized payment acceleration or fraudulent discount claims. Payment approval process review needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'high',
            title: 'Expense Report Manipulation Pattern',
            description: 'Employee expense report analysis reveals systematic pattern of claims just below approval threshold limit. 34 expense reports totaling $48K all within $50 of $1,000 delegation limit. This pattern consistent with splitting schemes to avoid higher-level review. Enhanced expense monitoring and audit sampling required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'critical',
            title: 'Fictitious Revenue Recognition Pattern',
            description: 'Customer order pattern analysis reveals suspicious characteristics: customers with no prior relationship, shipping addresses matching commercial mail receiving agencies, and rapid payment followed by credit notes. 18 transactions totaling $2.3M exhibit these red flags. Immediate customer verification and revenue reversal assessment required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'fraud_pattern',
            severity: 'high',
            title: 'Asset Misappropriation Indicators',
            description: 'Physical inventory reconciliation reveals systematic variances concentrated in high-value items with limited tracking controls. Shrinkage rate of 8% significantly exceeds industry norm of 2%. Pattern shows higher variances in periods with specific employee schedules. Enhanced inventory controls and forensic investigation recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },

        // RISK SPIKE ALERTS (10 total)
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'high',
            title: 'Risk Score Increased 15 Points in 30 Days',
            description: 'Overall risk score escalated from 65 to 80 over the past month driven by multiple deteriorating metrics including liquidity ratios, compliance violations, and operational anomalies. This rapid deterioration indicates systemic risk exposure requiring immediate management attention. Comprehensive risk mitigation strategy development and enhanced monitoring protocols recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'medium',
            title: 'Market Risk Exposure Spike Detected',
            description: 'Market risk exposure increased by 40% due to expanded foreign currency positions and commodity price volatility. Value-at-risk calculation shows potential $5M loss under stress scenarios. This elevated exposure requires review of hedging strategy and consideration of additional risk mitigation instruments.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'high',
            title: 'Credit Risk Score Deterioration',
            description: 'Customer credit risk score increased from 3.2 to 4.8 driven by higher days sales outstanding, increased bad debt write-offs, and declining credit quality metrics. Concentration risk also elevated with top 5 customers representing 60% of receivables. Enhanced credit monitoring and collection focus required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'medium',
            title: 'Operational Risk Level Elevated',
            description: 'Operational risk indicators show concerning trends: system downtime increased 35%, error rates in key processes up 25%, and employee turnover in critical roles accelerating. Combined operational risk score increased from 42 to 58. Process improvement initiatives and business continuity planning review needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'high',
            title: 'Liquidity Risk Score Increased 20%',
            description: 'Liquidity risk assessment deteriorated significantly with quick ratio declining to 0.8 and cash conversion cycle extending to 85 days. Available credit facilities decreased by 30% due to covenant pressure. This liquidity squeeze requires immediate cash flow optimization and alternative financing source evaluation.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'medium',
            title: 'Reputational Risk Indicators Rising',
            description: 'Reputational risk metrics showing negative trends: social media sentiment score declined 30%, customer complaint volume up 45%, and regulatory inquiry frequency increased. Media coverage tone increasingly negative with focus on operational issues. Proactive stakeholder communication and issue resolution strategy recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'high',
            title: 'Counterparty Risk Concentration Increased',
            description: 'Counterparty risk analysis reveals dangerous concentration with single supplier representing 45% of critical component purchases and limited alternative sources. Recent supplier financial distress indicators detected including payment delays to their vendors. Supply chain diversification and contingency planning urgently needed.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'medium',
            title: 'Regulatory Risk Score Elevated',
            description: 'Regulatory risk profile increased due to pending regulatory changes, increased examination activity, and evolving compliance requirements. Risk score increased from 35 to 52 driven by potential impact of new regulations and historical compliance deficiencies. Enhanced regulatory monitoring and compliance program strengthening recommended.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'resolved',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: getResolvedDate(getAcknowledgedDate(getRandomDateWithinLast30Days())),
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'low',
            title: 'Strategic Risk Assessment Deteriorated',
            description: 'Strategic risk indicators show concerning patterns: market share decline of 3%, competitive intensity increasing, and technology disruption threats rising. Strategic risk score increased from 28 to 38. While not immediate crisis, trend requires strategic planning review and competitive positioning assessment.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'acknowledged',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: getAcknowledgedDate(getRandomDateWithinLast30Days()),
            resolvedAt: null,
        },
        {
            userId: null,
            alertType: 'risk_spike',
            severity: 'high',
            title: 'Cybersecurity Risk Level Increased',
            description: 'Cybersecurity risk profile elevated due to increased attack frequency, detection of new vulnerabilities in critical systems, and expanding attack surface from remote work infrastructure. Threat intelligence indicates sector-targeted campaigns. Immediate security assessment, patch management acceleration, and incident response plan refresh required.',
            sourceDocumentId: getRandomDocumentId(),
            status: 'open',
            triggeredAt: getRandomDateWithinLast30Days(),
            acknowledgedAt: null,
            resolvedAt: null,
        },
    ];

    await db.insert(alerts).values(sampleAlerts);

    console.log('✅ Alerts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});