import { db } from '@/db';
import { complianceChecks } from '@/db/schema';

async function main() {
    const sampleComplianceChecks = [
        // IFRS Compliance Checks (21 total)
        // Revenue Recognition - IFRS 15 (5 checks)
        {
            documentId: 12,
            standardType: 'IFRS',
            checkName: 'Revenue Recognition - IFRS 15 Performance Obligations',
            result: 'fail',
            details: 'Revenue recognition timing does not comply with IFRS 15 - multiple performance obligations not properly separated. Software license revenue bundled with implementation services recognized upfront rather than over time. Recommend unbundling and recognizing implementation revenue over service period.',
            recommendation: 'Engage revenue recognition specialist to review contract portfolio. Implement systematic approach to identify distinct performance obligations. Update revenue recognition policy to defer service revenue over implementation period.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 34,
            standardType: 'IFRS',
            checkName: 'Revenue Recognition - IFRS 15 Variable Consideration',
            result: 'fail',
            details: 'Step 5 allocation of transaction price incorrect - variable consideration for performance bonuses not constrained appropriately. High probability of significant revenue reversal exists. Requires remeasurement using expected value method with historical data analysis.',
            recommendation: 'Apply constraint to variable consideration estimate using expected value method. Incorporate 3-year historical achievement rates. Disclose constraint methodology in revenue recognition policy note.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 56,
            standardType: 'IFRS',
            checkName: 'Revenue Recognition - IFRS 15 Contract Modifications',
            result: 'warning',
            details: 'Contract modification accounting unclear - amendment treated as separate contract when should be accounted for as modification of existing contract per IFRS 15.21. Impact immaterial at $250K but methodology needs correction for future modifications.',
            recommendation: 'Review contract modification decision tree. Reassess whether modified goods/services are distinct and priced at standalone selling price. Update accounting manual with clear modification examples.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 23,
            standardType: 'IFRS',
            checkName: 'Revenue Recognition - IFRS 15 Five-Step Model',
            result: 'pass',
            details: 'Five-step revenue recognition model properly applied across construction contracts. Performance obligations clearly identified, transaction price appropriately allocated using cost-to-cost input method. Revenue recognized as control transfers over time with reliable progress measurement.',
            recommendation: 'Continue current approach. Consider quarterly training for project managers on identifying new performance obligations when contract scope changes.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 45,
            standardType: 'IFRS',
            checkName: 'Revenue Recognition - IFRS 15 Principal vs Agent',
            result: 'pass',
            details: 'Principal vs agent analysis correctly performed for marketplace transactions. Company appropriately reports net commission revenue as agent rather than gross transaction value. Control indicators properly assessed per IFRS 15.B35-B37.',
            recommendation: 'Maintain current methodology. Document control assessment for each new product category added to marketplace platform.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Asset Valuation - IAS 36, IFRS 9 (5 checks)
        {
            documentId: 8,
            standardType: 'IFRS',
            checkName: 'Goodwill Impairment Testing - IAS 36',
            result: 'fail',
            details: 'Goodwill impairment testing incomplete under IAS 36 - no evidence of annual impairment test for CGU acquired in 2022. Carrying value $45M exceeds recoverable amount by estimated $8M based on preliminary value-in-use calculation. Requires formal impairment charge.',
            recommendation: 'Engage external valuation firm to perform comprehensive value-in-use calculation. Prepare discounted cash flow model with 5-year projections and terminal value. Record impairment loss and enhance disclosure of key assumptions.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 67,
            standardType: 'IFRS',
            checkName: 'Expected Credit Loss Model - IFRS 9',
            result: 'pass',
            details: 'Expected credit loss model under IFRS 9 appropriately applied - forward-looking information incorporated including GDP forecasts and industry-specific indicators. Staging logic correct with 30-day past due threshold. Lifetime ECL properly calculated for Stage 2 assets using probability-weighted scenarios.',
            recommendation: 'Continue current ECL methodology. Consider quarterly update of forward-looking macroeconomic assumptions rather than annual refresh to improve responsiveness.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 29,
            standardType: 'IFRS',
            checkName: 'Fair Value Measurement - IFRS 13 Level 3 Assets',
            result: 'fail',
            details: 'Fair value hierarchy Level 3 assets lack sufficient documentation of valuation methodology per IFRS 13. Unobservable inputs for private equity investments totaling $32M not properly disclosed or justified. Sensitivity analysis missing. Requires enhanced documentation and disclosure.',
            recommendation: 'Engage valuation specialist to document Level 3 fair value methodologies. Prepare detailed memo explaining unobservable inputs, selection of discount rates, and comparable transaction analysis. Perform sensitivity analysis on key assumptions.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 51,
            standardType: 'IFRS',
            checkName: 'Property Plant Equipment - IAS 16 Revaluation',
            result: 'pass',
            details: 'Property, plant and equipment revaluation model properly applied under IAS 16. Independent valuation obtained for land and buildings class. Revaluation surplus correctly recognized in OCI. Accumulated depreciation eliminated against gross carrying amount on revaluation date.',
            recommendation: 'Maintain triennial revaluation cycle. Ensure consistent application across entire asset class to avoid selective revaluation.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 73,
            standardType: 'IFRS',
            checkName: 'Investment Property - IAS 40 Fair Value Model',
            result: 'pass',
            details: 'Investment property measured at fair value through P&L per IAS 40. External appraisals obtained for properties exceeding $5M threshold. Valuation techniques include income capitalization and discounted cash flow. Fair value gains of $3.2M properly recognized in profit or loss.',
            recommendation: 'Continue annual external valuations. Consider internal desktop valuations for mid-year reporting to identify potential impairment triggers earlier.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Disclosure Requirements - IFRS 7, IAS 24 (5 checks)
        {
            documentId: 15,
            standardType: 'IFRS',
            checkName: 'Related Party Disclosures - IAS 24',
            result: 'fail',
            details: 'Related party transaction disclosures incomplete per IAS 24 - key management compensation details missing including separation of short-term and post-employment benefits. Intercompany loan terms not disclosed. Related party sales transactions aggregated without detail on nature, amounts, and outstanding balances.',
            recommendation: 'Prepare comprehensive related party disclosure note breaking down all transaction types. Include compensation by category, loan terms including interest rates, and aging of receivables/payables. Implement quarterly related party transaction tracking template.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 42,
            standardType: 'IFRS',
            checkName: 'Financial Instrument Risk Disclosures - IFRS 7',
            result: 'warning',
            details: 'Financial instrument risk disclosures under IFRS 7 lack quantitative sensitivity analysis for market risk exposures. Qualitative discussion of interest rate and foreign exchange risk provided but stress testing scenarios not quantified with impact on profit and equity.',
            recommendation: 'Develop standardized sensitivity analysis showing impact of reasonably possible changes in risk variables. Use 100 basis point parallel shift for interest rate risk and 10% change for FX risk as starting point. Update annually based on portfolio composition.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 58,
            standardType: 'IFRS',
            checkName: 'Revenue Disaggregation - IFRS 15 Disclosure',
            result: 'pass',
            details: 'Revenue disaggregation by geographic region, product line, and timing meets IFRS 15 disclosure requirements. Reconciliation to reportable segments provided showing how disaggregated revenue relates to segment revenue. Contract balances and performance obligations clearly disclosed.',
            recommendation: 'Continue current disaggregation approach. Consider adding customer concentration disclosure if single customer exceeds 10% of total revenue.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 81,
            standardType: 'IFRS',
            checkName: 'Significant Accounting Policies - IAS 1',
            result: 'pass',
            details: 'Significant accounting policy disclosures comply with IAS 1 requirements. Measurement bases clearly stated. Judgments and estimates that have significant effect on amounts recognized properly disclosed including useful lives, provisions, and fair value measurements.',
            recommendation: 'Maintain current disclosure quality. Review policy note annually to remove boilerplate and enhance discussion of entity-specific judgments.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 36,
            standardType: 'IFRS',
            checkName: 'Operating Segments - IFRS 8',
            result: 'pass',
            details: 'Operating segment identification and reporting complies with IFRS 8. Segments aligned with internal reporting to chief operating decision maker. Segment profit measure reconciled to consolidated profit. Geographic revenue and non-current asset disclosures provided.',
            recommendation: 'Monitor for changes in organizational structure or internal reporting that might affect segment identification. Update segment disclosure if new operating segments emerge.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Lease Accounting - IFRS 16 (3 checks)
        {
            documentId: 19,
            standardType: 'IFRS',
            checkName: 'Right-of-Use Assets - IFRS 16 Recognition',
            result: 'pass',
            details: 'Right-of-use assets and lease liabilities properly recognized under IFRS 16 for all leases except short-term and low-value exemptions. Discount rate determination reasonable using incremental borrowing rate of 6.5%. Initial direct costs appropriately capitalized as part of ROU asset.',
            recommendation: 'Continue current lease accounting approach. Update discount rate annually or when new leases commence to reflect current economic conditions.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 64,
            standardType: 'IFRS',
            checkName: 'Lease Modifications - IFRS 16',
            result: 'fail',
            details: 'Lease modification not properly accounted for - COVID-19 rent reduction treated as negative variable lease payment rather than lease modification per IFRS 16.46. Should remeasure lease liability at revised discount rate and adjust ROU asset. Total impact $450K across 12 property leases.',
            recommendation: 'Correct lease modification accounting by remeasuring lease liability for rent concessions. Adjust ROU asset for difference between remeasured liability and rent forgiveness. Update lease accounting policy to address modification scenarios.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 77,
            standardType: 'IFRS',
            checkName: 'Lease Term Assessment - IFRS 16',
            result: 'pass',
            details: 'Lease term properly includes non-cancellable period plus periods covered by extension options when reasonably certain to exercise. Assessment considers economic incentives including leasehold improvements, favorable terms, and business importance of leased assets.',
            recommendation: 'Reassess lease term annually or when significant events occur. Document rationale for extension option exercise decisions in lease evaluation memo.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Consolidation and Business Combinations (3 checks)
        {
            documentId: 27,
            standardType: 'IFRS',
            checkName: 'Business Combination - IFRS 3 Purchase Price Allocation',
            result: 'pass',
            details: 'Business combination accounting complies with IFRS 3. Purchase price allocation to identifiable assets and liabilities completed within measurement period. Goodwill represents future economic benefits from synergies. Contingent consideration liability measured at fair value.',
            recommendation: 'Finalize purchase price allocation before measurement period expires. Obtain third-party valuation for significant intangible assets including customer relationships and technology.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 49,
            standardType: 'IFRS',
            checkName: 'Consolidation - IFRS 10 Control Assessment',
            result: 'pass',
            details: 'Control assessment under IFRS 10 properly performed. Subsidiary meeting definition of control through voting rights and ability to direct relevant activities. Non-controlling interests appropriately measured and presented in consolidated financial statements.',
            recommendation: 'Maintain annual control assessment documentation. Monitor for changes in voting rights, contractual arrangements, or de facto control circumstances.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 85,
            standardType: 'IFRS',
            checkName: 'Joint Arrangements - IFRS 11',
            result: 'pass',
            details: 'Joint arrangement correctly classified as joint operation based on contractual rights to assets and obligations for liabilities. Entity recognizes its share of assets, liabilities, revenues and expenses rather than equity method investment.',
            recommendation: 'Review joint arrangement classification whenever contractual terms are amended. Ensure accounting treatment aligns with legal form and substance of arrangement.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // GAAP Compliance Checks (18 total)
        // Revenue Recognition - ASC 606 (4 checks)
        {
            documentId: 11,
            standardType: 'GAAP',
            checkName: 'Revenue Recognition - ASC 606 Principal vs Agent',
            result: 'fail',
            details: 'Principal vs agent determination incorrect under ASC 606 - company acting as agent but recognizing gross revenue of $18.5M. Control indicators assessment shows company does not obtain control before transfer to customer. Should report net basis as commission earned at $2.3M.',
            recommendation: 'Restate revenue to net commission basis. Revise revenue recognition policy documentation. Train sales operations team on proper classification of new product arrangements as principal or agent relationships.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 38,
            standardType: 'GAAP',
            checkName: 'Revenue Recognition - ASC 606 Five-Step Model',
            result: 'pass',
            details: 'Five-step revenue recognition model properly applied across product portfolio. Performance obligations clearly identified in standard contracts. Transaction price appropriately allocated using standalone selling prices determined through cost-plus margin approach. Revenue recognized as control transfers at point of shipment.',
            recommendation: 'Continue current revenue recognition methodology. Consider implementing automated contract review tool as transaction volume increases to maintain consistency.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 62,
            standardType: 'GAAP',
            checkName: 'Revenue Recognition - ASC 606 Contract Assets and Liabilities',
            result: 'pass',
            details: 'Contract assets and liabilities properly recognized and presented. Unbilled receivables for completed performance obligations classified as contract assets. Advance payments received classified as contract liabilities with appropriate revenue recognition as obligations satisfied.',
            recommendation: 'Maintain current contract asset/liability tracking. Enhance disclosure to show opening balance reconciliation to closing balance including contract modifications during period.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 74,
            standardType: 'GAAP',
            checkName: 'Revenue Recognition - ASC 606 Practical Expedients',
            result: 'pass',
            details: 'Practical expedients appropriately applied under ASC 606. Significant financing component assessment exemption used for contracts with payment within one year. Incremental costs of obtaining contracts expensed as incurred given amortization period less than one year.',
            recommendation: 'Document practical expedient elections in revenue recognition policy. Monitor contract payment terms to ensure financing component exemption remains applicable.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Asset Valuation - ASC 350, ASC 360 (4 checks)
        {
            documentId: 25,
            standardType: 'GAAP',
            checkName: 'Intangible Assets - ASC 350 Amortization',
            result: 'fail',
            details: 'Intangible asset amortization period exceeds useful life - customer relationships amortized over 15 years when evidence suggests 8-year average retention based on historical churn analysis. Technology intangibles amortized over 10 years despite 5-year product life cycle. Accelerated amortization required totaling estimated $3.2M catch-up.',
            recommendation: 'Engage valuation specialist to reassess useful lives of intangible assets. Accelerate amortization to align with economic benefit realization period. Update amortization policy with clear methodology for useful life determination.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 47,
            standardType: 'GAAP',
            checkName: 'Capitalized Software Development - ASC 985-20',
            result: 'warning',
            details: 'Capitalized software development costs borderline for technological feasibility milestone under ASC 985-20. Working model exists but detailed program design not fully completed. Capitalization of $1.8M during quarter may be premature. Consider more conservative expense recognition until coding substantially complete.',
            recommendation: 'Implement formal stage-gate process for software development capitalization. Document technological feasibility milestone with detailed program design and project plan. Enhance supporting documentation for capitalization decision.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 53,
            standardType: 'GAAP',
            checkName: 'Long-Lived Assets - ASC 360 Impairment',
            result: 'pass',
            details: 'Long-lived asset impairment testing properly performed under ASC 360. Recoverability test applied when triggering events identified. Undiscounted cash flow analysis supports carrying value for asset groups tested. No impairment losses recognized during period.',
            recommendation: 'Continue monitoring for impairment indicators quarterly. Document rationale when triggering events occur but impairment testing not performed due to immateriality.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 69,
            standardType: 'GAAP',
            checkName: 'Goodwill - ASC 350 Annual Impairment Test',
            result: 'pass',
            details: 'Goodwill impairment testing complies with ASC 350. Qualitative assessment performed concluding more-likely-than-not that fair value exceeds carrying value for all reporting units. Goodwill allocated to reporting units based on expected benefit from business combination synergies.',
            recommendation: 'Maintain documentation of qualitative factors supporting conclusion. Consider quantitative testing every 3 years even if qualitative assessment passes to validate assumptions.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Disclosure Requirements - ASC 820, ASC 280 (3 checks)
        {
            documentId: 16,
            standardType: 'GAAP',
            checkName: 'Segment Reporting - ASC 280',
            result: 'fail',
            details: 'Segment reporting under ASC 280 does not align with CODM reporting structure - three operating segments identified internally (Enterprise Software, Cloud Services, Consulting) but reported as two reportable segments with Cloud and Consulting inappropriately aggregated. Economic characteristics differ significantly preventing aggregation.',
            recommendation: 'Revise segment reporting to present three separate reportable segments matching internal management reporting. Recast prior period comparatives. Update segment disclosure policy and enhance description of segment profit measures.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 41,
            standardType: 'GAAP',
            checkName: 'Fair Value Measurement - ASC 820 Hierarchy',
            result: 'pass',
            details: 'Fair value measurements properly categorized in three-level hierarchy per ASC 820. Level 1 quoted prices for marketable securities, Level 2 observable inputs for interest rate swaps, Level 3 unobservable inputs for contingent consideration. Rollforward provided reconciling Level 3 measurements with unrealized gains/losses.',
            recommendation: 'Continue current fair value measurement and disclosure approach. Consider enhancing narrative description of valuation techniques for Level 3 measurements.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 88,
            standardType: 'GAAP',
            checkName: 'Subsequent Events - ASC 855',
            result: 'pass',
            details: 'Subsequent events properly evaluated through financial statement issuance date per ASC 855. Material acquisition announced after balance sheet date appropriately disclosed as non-recognized subsequent event. Management reviewed all significant transactions and events through report date.',
            recommendation: 'Maintain subsequent event review procedures. Document evaluation date and cutoff procedures in audit file to support completeness of review.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Lease Accounting - ASC 842 (2 checks)
        {
            documentId: 14,
            standardType: 'GAAP',
            checkName: 'Operating Leases - ASC 842 Recognition',
            result: 'fail',
            details: 'Operating lease right-of-use asset and liability not recognized for lease terms exceeding 12 months per ASC 842. Transition from ASC 840 not properly implemented - 23 real estate and equipment leases not capitalized totaling $18.3M present value. Monthly rent expense incorrectly recognized rather than amortization and interest.',
            recommendation: 'Immediately implement ASC 842 modified retrospective transition approach. Engage lease accounting specialist to identify all in-scope contracts. Calculate lease liability as present value of remaining payments and recognize offsetting ROU asset.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 59,
            standardType: 'GAAP',
            checkName: 'Lease Classification - ASC 842',
            result: 'pass',
            details: 'Lease classification properly evaluated using five criteria under ASC 842. Equipment leases meeting finance lease criteria appropriately classified with asset and liability recognized. Operating leases correctly identified and accounted for with straight-line expense recognition over lease term.',
            recommendation: 'Continue current lease classification methodology. Update lease evaluation memo template to document assessment of all five classification criteria for each new lease.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Stock Compensation - ASC 718 (2 checks)
        {
            documentId: 31,
            standardType: 'GAAP',
            checkName: 'Stock-Based Compensation - ASC 718 Measurement',
            result: 'pass',
            details: 'Stock-based compensation expense properly measured at grant date fair value using Black-Scholes option pricing model per ASC 718. Reasonable assumptions used including expected volatility of 45% based on historical stock price, expected term of 6 years using simplified method, and risk-free rate of 4.2%. Forfeitures estimated using 15% rate based on 3-year historical pattern.',
            recommendation: 'Continue current stock compensation measurement approach. Review assumptions annually and update for significant changes in company circumstances or volatility patterns.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 76,
            standardType: 'GAAP',
            checkName: 'Stock-Based Compensation - ASC 718 Modifications',
            result: 'pass',
            details: 'Stock option modification properly accounted for as Type I modification requiring incremental compensation cost recognition. Fair value immediately before and after modification calculated. Incremental value of $420K recognized over remaining vesting period. Disclosure includes modification terms and rationale.',
            recommendation: 'Maintain documentation of modification analysis including fair value calculations. Consider establishing equity award modification policy requiring compensation committee approval.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Income Taxes and Other (3 checks)
        {
            documentId: 22,
            standardType: 'GAAP',
            checkName: 'Income Taxes - ASC 740 Uncertain Tax Positions',
            result: 'pass',
            details: 'Uncertain tax positions properly evaluated under ASC 740 two-step recognition and measurement approach. Tax benefits recognized only when more-likely-than-not to be sustained upon examination. Measurement reflects largest amount with greater than 50% likelihood. Reconciliation of unrecognized tax benefits provided.',
            recommendation: 'Continue annual evaluation of uncertain tax positions. Monitor for changes in tax law or examination activity affecting likelihood of realization.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 68,
            standardType: 'GAAP',
            checkName: 'Contingencies - ASC 450 Loss Contingencies',
            result: 'pass',
            details: 'Loss contingencies properly evaluated under ASC 450. Pending litigation accrued at $2.5M representing best estimate within range of probable loss. Remote contingencies appropriately disclosed without accrual. Management consulted with legal counsel to assess probability and estimate potential loss.',
            recommendation: 'Maintain quarterly legal contingency assessment process. Document basis for probability conclusions and loss estimate calculations in attorney response letters.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 82,
            standardType: 'GAAP',
            checkName: 'Earnings Per Share - ASC 260',
            result: 'pass',
            details: 'Earnings per share calculation complies with ASC 260. Basic EPS uses weighted-average shares outstanding. Diluted EPS includes dilutive effect of stock options using treasury stock method with average market price exceeding exercise price. Anti-dilutive securities appropriately excluded from diluted EPS.',
            recommendation: 'Continue current EPS calculation methodology. Consider enhancing disclosure to show reconciliation of numerator and denominator for basic and diluted EPS.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // SEBI Compliance Checks (11 total)
        // Disclosure Requirements (5 checks)
        {
            documentId: 3,
            standardType: 'SEBI',
            checkName: 'Related Party Transactions - SEBI LODR Regulation 23',
            result: 'fail',
            details: 'Related party transactions not disclosed per SEBI LODR Regulation 23 requirements - 4 material transactions with promoter group entities totaling ₹850 lakhs not reported in quarterly financial results. Transaction with affiliate company for purchase of raw materials at ₹320 lakhs exceeded materiality threshold but not disclosed to audit committee or stock exchange.',
            recommendation: 'Immediately disclose all material related party transactions to audit committee and stock exchange. Implement RPT tracking system to capture all transactions quarterly. Obtain audit committee approval before entering future material RPTs.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 21,
            standardType: 'SEBI',
            checkName: 'Insider Trading - SEBI PIT Regulations',
            result: 'pass',
            details: 'Insider trading window closure properly maintained and disclosed per SEBI PIT Regulations. Trading window closed 7 days before board meeting and reopened 48 hours after financial results announcement. All trades by designated persons reported within required 2 trading day timeframe. No violations detected during review period.',
            recommendation: 'Continue current insider trading compliance framework. Consider implementing automated PMS demat account monitoring system to detect trades during closure period.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 44,
            standardType: 'SEBI',
            checkName: 'Corporate Governance - SEBI LODR Regulation 27',
            result: 'warning',
            details: 'Corporate governance report submitted but composition of board committees not fully compliant - audit committee has 2 independent directors and 1 non-executive director, should have all independent directors per SEBI LODR Regulation 18. Nomination and remuneration committee meets composition requirements. Stakeholders relationship committee functioning properly.',
            recommendation: 'Reconstitute audit committee to include only independent directors. Replace non-executive non-independent director with independent director at next board meeting. Update committee charter to reflect proper composition.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 55,
            standardType: 'SEBI',
            checkName: 'Annual Report - SEBI LODR Regulation 34',
            result: 'pass',
            details: 'Annual report complies with SEBI LODR Regulation 34 disclosure requirements. Management discussion and analysis covers industry structure, opportunities, threats, risks, and outlook. Corporate governance report includes all mandatory disclosures. Related party transaction policy disclosed on company website.',
            recommendation: 'Maintain current annual report disclosure standards. Consider adding more detailed business responsibility report covering ESG parameters in line with BRSR framework.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 71,
            standardType: 'SEBI',
            checkName: 'Materiality Disclosures - SEBI LODR Regulation 30',
            result: 'pass',
            details: 'Material event disclosures properly submitted to stock exchange within required timelines per SEBI LODR Regulation 30. Change in CEO disclosed within 24 hours. Acquisition announcement made before market opening. Loss of major customer disclosed with impact assessment on revenue.',
            recommendation: 'Continue proactive material event disclosure approach. Maintain event identification checklist and escalation matrix to ensure timely reporting.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Financial Reporting (4 checks)
        {
            documentId: 9,
            standardType: 'SEBI',
            checkName: 'Quarterly Results - SEBI LODR Regulation 33',
            result: 'pass',
            details: 'Quarterly financial results filed within 45 days of quarter end meeting SEBI LODR Regulation 33 timeline. Results format compliant with Ind AS requirements and SEBI circular. Limited review report from statutory auditors included. Standalone and consolidated results both submitted.',
            recommendation: 'Maintain current quarterly reporting timeline. Consider earlier filing target of 40 days to provide buffer for unforeseen delays.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 33,
            standardType: 'SEBI',
            checkName: 'Material Subsidiary - SEBI LODR Regulation 24',
            result: 'fail',
            details: 'Material subsidiary financial information not properly consolidated as required by SEBI LODR Regulation 24. Subsidiary representing 18% of consolidated revenue and meeting materiality threshold not included in quarterly consolidated results. Separate subsidiary board meeting minutes not reviewed by holding company audit committee.',
            recommendation: 'Immediately include material subsidiary in consolidated financial results. Appoint independent director on subsidiary board. Implement policy for audit committee review of subsidiary financial statements and significant transactions.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 61,
            standardType: 'SEBI',
            checkName: 'Audit Committee Review - SEBI LODR Regulation 18',
            result: 'pass',
            details: 'Audit committee functioning effectively per SEBI LODR Regulation 18 requirements. Quarterly financial statements reviewed before submission to board. Internal audit findings and risk management framework reviewed. Related party transactions evaluated for fairness. Recommendation to board on auditor appointment properly documented.',
            recommendation: 'Continue robust audit committee oversight. Consider increasing meeting frequency during peak reporting periods to provide more time for review.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 79,
            standardType: 'SEBI',
            checkName: 'Auditor Rotation - SEBI LODR Regulation 24A',
            result: 'pass',
            details: 'Audit firm rotation complies with SEBI requirements. Current audit firm in 4th year of engagement, within maximum 5-year term before mandatory rotation. Audit partner rotation completed after 5 years. Cooling-off period properly observed for outgoing audit partner.',
            recommendation: 'Begin audit firm RFP process in next fiscal year to ensure smooth transition before mandatory rotation deadline. Maintain documentation of partner rotation dates.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Other SEBI Requirements (2 checks)
        {
            documentId: 50,
            standardType: 'SEBI',
            checkName: 'Business Responsibility Report - SEBI LODR',
            result: 'pass',
            details: 'Business Responsibility and Sustainability Report submitted as part of annual report for Top 1000 listed companies. BRSR Core framework adopted with reasonable assurance from independent auditor. ESG disclosures cover environment, social, and governance parameters with quantitative metrics.',
            recommendation: 'Enhance sustainability reporting by setting specific ESG targets and timelines. Consider CDP and GRI reporting frameworks for comprehensive ESG disclosure.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 87,
            standardType: 'SEBI',
            checkName: 'Dividend Distribution - SEBI Guidelines',
            result: 'pass',
            details: 'Dividend distribution policy disclosed per SEBI requirements. Policy covers circumstances for dividend payment, financial parameters considered, and internal/external factors influencing decision. Board recommendation and shareholder approval properly documented. Dividend payment within 30 days of declaration.',
            recommendation: 'Review dividend distribution policy annually to ensure alignment with company financial performance and future capital requirements.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // SEC Compliance Checks (11 total)
        // Filing Requirements (3 checks)
        {
            documentId: 5,
            standardType: 'SEC',
            checkName: 'Form 10-Q Filing - SEC Rule 13a-13',
            result: 'fail',
            details: 'Form 10-Q filed 3 days past 45-day deadline for large accelerated filer per SEC Rule 13a-13. Late filing notification Form 12b-25 not submitted to SEC within required 1 business day after deadline. Subject to potential late filing fees and loss of Form S-3 eligibility for 12 months.',
            recommendation: 'Immediately file late notification with SEC explaining reasons for delay. Implement enhanced quarterly close timeline with built-in contingency days. Conduct lessons learned review to prevent future late filings.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 28,
            standardType: 'SEC',
            checkName: 'Management Discussion and Analysis - Item 303',
            result: 'pass',
            details: 'Management Discussion and Analysis sufficiently detailed meeting SEC Item 303 requirements. Known trends and uncertainties properly discussed including supply chain disruptions and raw material cost inflation. Liquidity and capital resources section covers short-term and long-term needs. Critical accounting estimates clearly explained.',
            recommendation: 'Continue comprehensive MD&A approach. Consider adding more forward-looking information about new product initiatives while maintaining appropriate cautionary language.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 65,
            standardType: 'SEC',
            checkName: 'Form 8-K Current Reports - Item 2.02',
            result: 'pass',
            details: 'Form 8-K current reports timely filed within 4 business days per SEC requirements. Earnings release properly disclosed under Item 2.02. Exhibit 99.1 includes full text of earnings press release. Material agreement execution disclosed under Item 1.01 with material terms summarized.',
            recommendation: 'Maintain current Form 8-K filing procedures. Update current report checklist annually to reflect any new SEC disclosure requirements.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Disclosure Controls (3 checks)
        {
            documentId: 17,
            standardType: 'SEC',
            checkName: 'Internal Controls - Item 9A Material Weakness',
            result: 'fail',
            details: 'Material weakness in internal controls over financial reporting not disclosed in Item 9A despite identification during SOX 404 testing. Revenue recognition process control failure allowing unsupported revenue accruals to be recorded. Material weakness determination made but disclosure omitted from Form 10-K.',
            recommendation: 'Immediately amend Form 10-K to disclose material weakness in Item 9A. Update management assessment of ICFR effectiveness. Develop and implement remediation plan with specific milestones. Consider hiring internal controls consultant.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 40,
            standardType: 'SEC',
            checkName: 'Risk Factors - Item 1A',
            result: 'warning',
            details: 'Risk factor disclosures under Item 1A generic and boilerplate - lack company-specific risk analysis and quantification. Cybersecurity risk discussed but no mention of specific incidents or vulnerabilities. While technically compliant with minimum requirements, disclosure quality could be substantially enhanced.',
            recommendation: 'Revise risk factor disclosures to include more company-specific information. Quantify risks where possible. Organize by category and prioritize by likelihood and magnitude. Remove immaterial boilerplate risks.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 72,
            standardType: 'SEC',
            checkName: 'Sarbanes-Oxley Certifications - Sections 302 and 906',
            result: 'pass',
            details: 'CEO and CFO certifications properly executed under Sections 302 and 906 of Sarbanes-Oxley Act. No exceptions or qualifications noted in certification language. Officers acknowledge responsibility for establishing and maintaining disclosure controls and procedures. ICFR assessment included in certification.',
            recommendation: 'Continue current certification process. Maintain sub-certification procedures for segment presidents and controllers to support CEO/CFO certifications.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Financial Statement Requirements (3 checks)
        {
            documentId: 24,
            standardType: 'SEC',
            checkName: 'Regulation S-X Compliance - Financial Statements',
            result: 'pass',
            details: 'Financial statements comply with SEC Regulation S-X presentation requirements. Balance sheet comparative format for 2 years provided. Income statement and cash flow statement comparative format for 3 years included. All required schedules filed. Audit report unqualified and properly formatted.',
            recommendation: 'Maintain current financial statement presentation. Monitor for any new Regulation S-X amendments that may affect future reporting requirements.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 54,
            standardType: 'SEC',
            checkName: 'Non-GAAP Financial Measures - Item 10(e)',
            result: 'pass',
            details: 'Non-GAAP financial measures properly reconciled to most directly comparable GAAP measures per Item 10(e) requirements. Adjusted EBITDA reconciliation includes all adjustments with clear descriptions. Equal or greater prominence given to GAAP measures. Use of non-GAAP measures explained and consistent across periods.',
            recommendation: 'Continue current non-GAAP presentation approach. Review SEC CF Disclosure Guidance annually to ensure ongoing compliance with evolving interpretations.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 86,
            standardType: 'SEC',
            checkName: 'Related Party Transactions - Item 404',
            result: 'pass',
            details: 'Related party transaction disclosure complies with Item 404 requirements. Transactions exceeding $120K threshold properly disclosed including parties involved, amounts, and terms. Director and executive officer transactions identified and described. Policies and procedures for reviewing RPTs disclosed.',
            recommendation: 'Maintain annual process for collecting related party transaction information through director and officer questionnaires. Consider lowering internal reporting threshold below $120K SEC requirement.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Other SEC Requirements (2 checks)
        {
            documentId: 48,
            standardType: 'SEC',
            checkName: 'Audit Committee Financial Expert - Item 407',
            result: 'pass',
            details: 'Audit committee financial expert properly designated and disclosed per Item 407 requirements. Director meets experience criteria including understanding of GAAP and financial statements, experience applying GAAP, experience with internal controls, and understanding of audit committee functions.',
            recommendation: 'Maintain documentation of financial expert qualification assessment. Update disclosure if financial expert changes or additional expert added to committee.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 83,
            standardType: 'SEC',
            checkName: 'Executive Compensation - Item 402',
            result: 'pass',
            details: 'Executive compensation disclosure complies with Item 402 requirements. Summary compensation table includes all required columns. Grants of plan-based awards table properly presented. Narrative discussion explains compensation decisions and policy. Pay ratio disclosure calculated per required methodology.',
            recommendation: 'Continue comprehensive compensation disclosure. Monitor for new SEC pay versus performance disclosure requirements and implement when effective.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // SOX Compliance Checks (7 total)
        // Internal Controls - SOX 404 (5 checks)
        {
            documentId: 6,
            standardType: 'SOX',
            checkName: 'Revenue Recognition Controls - SOX 404',
            result: 'fail',
            details: 'Material weakness identified in revenue recognition controls - no secondary review of complex contracts with multiple performance obligations and variable consideration. Three instances discovered where revenue recognized prematurely without proper performance obligation analysis. Revenue potentially overstated by estimated $2.8M.',
            recommendation: 'Implement mandatory contract review committee for all contracts exceeding $500K or containing complex terms. Develop revenue recognition checklist aligned with ASC 606 five-step model. Provide training to sales operations and accounting teams. Engage Big 4 technical accounting advisor.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 30,
            standardType: 'SOX',
            checkName: 'IT General Controls - SOX 404',
            result: 'fail',
            details: 'Significant deficiency in IT general controls - segregation of duties not maintained in financial ERP system. Single system administrator has ability to both post journal entries and approve them without supervisory review. Change management process lacks proper testing and approval documentation. Represents elevated risk of financial misstatement.',
            recommendation: 'Immediately implement segregation of duties in financial system by removing posting rights from administrator role. Create separate approver profile. Implement IT change management policy requiring development, testing, and production environment separation. Conduct access rights review quarterly.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 52,
            standardType: 'SOX',
            checkName: 'Entity-Level Controls - SOX 404',
            result: 'pass',
            details: 'Entity-level controls operating effectively providing strong control environment foundation. Tone at top demonstrated through ethical leadership and accountability. Code of conduct enforced with annual certification. Whistleblower hotline functional and independently administered. Audit committee provides effective oversight of financial reporting and internal controls.',
            recommendation: 'Continue emphasis on entity-level controls. Consider conducting culture survey to assess tone at top effectiveness and identify improvement opportunities.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 66,
            standardType: 'SOX',
            checkName: 'Period-End Financial Close Controls - SOX 404',
            result: 'warning',
            details: 'Control over period-end financial close process relies heavily on manual Excel-based reconciliations increasing error risk. Month-end close takes 12 days with multiple iterations. Account reconciliation review not consistently documented. While no errors detected, process efficiency and control documentation need improvement.',
            recommendation: 'Implement automated reconciliation tool to replace manual Excel workbooks. Establish standard close calendar with clear deliverable deadlines. Require electronic sign-off for all account reconciliation reviews. Target 7-day close timeline.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 80,
            standardType: 'SOX',
            checkName: 'Accounts Payable and Procurement Controls - SOX 404',
            result: 'pass',
            details: 'Accounts payable and procurement controls properly designed and operating effectively. Three-way match enforced between purchase order, receiving document, and vendor invoice. Vendor master file changes require dual approval from procurement and AP supervisor. Purchase order authorization limits by role properly configured and monitored.',
            recommendation: 'Continue current control design. Consider implementing automated duplicate payment detection tool as transaction volume increases.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Management Assessment and Reporting (2 checks)
        {
            documentId: 43,
            standardType: 'SOX',
            checkName: 'Management ICFR Assessment - SOX 404(a)',
            result: 'pass',
            details: 'Management assessment of internal control effectiveness over financial reporting properly documented per SOX Section 404(a). Testing scope covers all significant accounts and disclosures. Control deficiencies appropriately evaluated for severity. Workpaper documentation supports management conclusion. Assessment signed by CEO and CFO.',
            recommendation: 'Maintain comprehensive SOX documentation approach. Update risk assessment annually to ensure testing scope remains appropriate as business changes.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 89,
            standardType: 'SOX',
            checkName: 'External Auditor ICFR Attestation - SOX 404(b)',
            result: 'pass',
            details: 'External auditor attestation report on internal control over financial reporting issued without qualification per SOX Section 404(b). Auditor testing performed using PCAOB AS 2201 integrated audit approach. No material weaknesses or significant deficiencies identified. Opinion states controls are effective as of fiscal year-end date.',
            recommendation: 'Coordinate with external auditor early in process to align on scope and timing. Provide complete SOX documentation packages to optimize audit efficiency.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Basel III Compliance Checks (2 total)
        {
            documentId: 2,
            standardType: 'Basel III',
            checkName: 'Capital Adequacy - CET1 Ratio',
            result: 'fail',
            details: 'Common Equity Tier 1 ratio at 9.2% below required minimum of 10.5% including 2.5% capital conservation buffer per Basel III framework. Risk-weighted assets increased 18% due to loan portfolio growth while CET1 capital increased only 8%. Bank operating within minimum regulatory capital buffer triggering restrictions on dividends and bonus payments.',
            recommendation: 'Develop capital raise plan through equity issuance or retained earnings accumulation. Consider strategic options to reduce risk-weighted assets including loan portfolio optimization or asset sales. Submit capital restoration plan to regulatory authority within 30 days.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            documentId: 18,
            standardType: 'Basel III',
            checkName: 'Liquidity Coverage Ratio - LCR',
            result: 'pass',
            details: 'Liquidity Coverage Ratio at 128% exceeds minimum 100% requirement under Basel III liquidity standards. High-quality liquid assets of $450M sufficient to cover projected net cash outflows of $352M under 30-day stress scenario. HQLA composition appropriately diversified across Level 1 and Level 2A assets with no Level 2B assets.',
            recommendation: 'Maintain LCR above 110% target with buffer for intraday volatility. Monitor deposit concentration and funding diversification. Update stress testing assumptions quarterly based on market conditions.',
            checkedAt: new Date(Date.now() - Math.floor(Math.random() * 45) * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(complianceChecks).values(sampleComplianceChecks);
    
    console.log('✅ Comprehensive compliance checks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});