import { db } from '@/db';
import { documents } from '@/db/schema';

async function main() {
    const baseDate = new Date();
    const getRandomDate = (daysBack: number) => {
        const date = new Date(baseDate);
        date.setDate(date.getDate() - Math.floor(Math.random() * daysBack));
        return date.toISOString();
    };

    const getRandomFileSize = () => Math.floor(Math.random() * (12000000 - 800000) + 800000);

    const sampleDocuments = [
        // Company 1 - Apple (8 documents)
        {
            userId: null,
            fileName: 'AAPL_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Annual report showing strong revenue growth driven by iPhone 15 sales and services expansion. Total revenue reached $383.3B with gross margin of 44.1%.',
            storagePath: '/uploads/2024/12/AAPL_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Apple_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 0,
            complianceStatus: 'Pass',
            summary: 'Q3 quarterly report with revenue of $85.8B, up 5% YoY. Services revenue set new all-time record of $24.2B.',
            storagePath: '/uploads/2024/11/Apple_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Apple_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Balance sheet shows total assets of $352.8B with strong cash position of $162.1B and shareholder equity of $90.5B.',
            storagePath: '/uploads/2024/11/Apple_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'AAPL_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/10/AAPL_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Apple_Income_Statement_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Q4 income statement showing net income of $22.9B with operating margin of 29.8% and EPS of $1.46.',
            storagePath: '/uploads/2024/12/Apple_Income_Statement_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Apple_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Annual cash flow statement with operating cash flow of $110.5B and free cash flow of $99.6B after capital expenditures.',
            storagePath: '/uploads/2024/11/Apple_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'AAPL_10Q_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 4,
            complianceStatus: 'Review',
            summary: 'Q2 report with revenue of $90.8B, minor inventory adjustments noted requiring further review for accuracy.',
            storagePath: '/uploads/2024/10/AAPL_10Q_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Apple_Annual_Report_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'failed',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/12/Apple_Annual_Report_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 2 - Microsoft (7 documents)
        {
            userId: null,
            fileName: 'MSFT_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 0,
            complianceStatus: 'Pass',
            summary: 'Annual report with total revenue of $245.1B, up 15% driven by cloud services growth. Azure revenue grew 29% YoY.',
            storagePath: '/uploads/2024/12/MSFT_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Microsoft_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 5,
            complianceStatus: 'Review',
            summary: 'Q4 results showing revenue of $64.7B. Some discrepancies in deferred revenue recognition patterns detected.',
            storagePath: '/uploads/2024/11/Microsoft_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Microsoft_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Balance sheet with total assets of $512.2B, including cash and equivalents of $144.7B.',
            storagePath: '/uploads/2024/11/Microsoft_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'MSFT_10Q_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/10/MSFT_10Q_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Microsoft_Income_Statement_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'high',
            anomalyCount: 8,
            complianceStatus: 'Failed',
            summary: 'Q3 income statement with significant unexplained variances in operating expenses and R&D costs requiring investigation.',
            storagePath: '/uploads/2024/11/Microsoft_Income_Statement_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Microsoft_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 4,
            complianceStatus: 'Review',
            summary: 'Cash flow statement showing operating cash flow of $87.6B with some timing differences in capital expenditure reporting.',
            storagePath: '/uploads/2024/12/Microsoft_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'MSFT_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Q1 quarterly report with revenue of $56.5B, net income of $22.3B, demonstrating strong cloud computing demand.',
            storagePath: '/uploads/2024/09/MSFT_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 3 - JPMorgan (8 documents)
        {
            userId: null,
            fileName: 'JPM_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 6,
            complianceStatus: 'Review',
            summary: 'Annual report showing total revenue of $158.1B with net interest income of $89.3B. Some loan loss provision calculations require review.',
            storagePath: '/uploads/2024/12/JPM_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JPMorgan_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'high',
            anomalyCount: 10,
            complianceStatus: 'Failed',
            summary: 'Q3 report with revenue of $41.7B. Significant anomalies detected in trading revenue and derivative valuations.',
            storagePath: '/uploads/2024/11/JPMorgan_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JPMorgan_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'failed',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/11/JPMorgan_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JPM_10Q_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Q4 quarterly filing showing net income of $13.2B and ROE of 16%. Capital ratios remain well above regulatory requirements.',
            storagePath: '/uploads/2024/12/JPM_10Q_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JPMorgan_Income_Statement_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/10/JPMorgan_Income_Statement_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JPMorgan_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 5,
            complianceStatus: 'Review',
            summary: 'Cash flow statement with operating activities generating $52.7B. Some classifications between operating and financing activities need verification.',
            storagePath: '/uploads/2024/11/JPMorgan_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JPM_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Q1 report with total revenue of $42.6B and managed assets of $3.9T. Credit quality metrics remain stable.',
            storagePath: '/uploads/2024/09/JPM_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JPMorgan_Annual_Report_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Comprehensive annual report highlighting investment banking fees of $8.2B and continued expansion in wealth management.',
            storagePath: '/uploads/2024/12/JPMorgan_Annual_Report_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 4 - Goldman Sachs (7 documents)
        {
            userId: null,
            fileName: 'GS_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 7,
            complianceStatus: 'Review',
            summary: 'Annual report with net revenues of $46.2B. Elevated trading volatility and unusual concentration in certain derivative positions detected.',
            storagePath: '/uploads/2024/12/GS_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'GoldmanSachs_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'high',
            anomalyCount: 11,
            complianceStatus: 'Failed',
            summary: 'Q2 report showing net revenues of $12.7B. Critical discrepancies in fair value measurements of Level 3 assets.',
            storagePath: '/uploads/2024/10/GoldmanSachs_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'GoldmanSachs_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/11/GoldmanSachs_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'GS_10Q_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Q3 quarterly filing with net income of $3.0B. Investment banking revenues up 24% YoY driven by M&A activity.',
            storagePath: '/uploads/2024/11/GS_10Q_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'GoldmanSachs_Income_Statement_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 4,
            complianceStatus: 'Pass',
            summary: 'Q1 income statement with total revenues of $14.2B. Minor inconsistencies in compensation expense accruals.',
            storagePath: '/uploads/2024/09/GoldmanSachs_Income_Statement_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'GoldmanSachs_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Annual cash flow statement showing significant cash from financing activities of $34.5B primarily from debt issuance.',
            storagePath: '/uploads/2024/12/GoldmanSachs_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'GS_10Q_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'failed',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/12/GS_10Q_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 5 - Tesla (8 documents)
        {
            userId: null,
            fileName: 'TSLA_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Annual report with revenue of $96.8B, delivering 1.81M vehicles. Strong energy generation and storage segment growth of 54%.',
            storagePath: '/uploads/2024/12/TSLA_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Tesla_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 6,
            complianceStatus: 'Review',
            summary: 'Q4 quarterly report with automotive revenue of $19.9B. Inventory levels and production ramp metrics require further analysis.',
            storagePath: '/uploads/2024/12/Tesla_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Tesla_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Balance sheet showing total assets of $106.6B with cash and investments of $29.1B and minimal debt.',
            storagePath: '/uploads/2024/11/Tesla_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'TSLA_10Q_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/10/TSLA_10Q_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Tesla_Income_Statement_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'high',
            anomalyCount: 9,
            complianceStatus: 'Failed',
            summary: 'Q3 income statement with revenue of $23.4B. Significant unexplained fluctuations in warranty reserves and R&D capitalization.',
            storagePath: '/uploads/2024/11/Tesla_Income_Statement_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Tesla_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 5,
            complianceStatus: 'Review',
            summary: 'Cash flow statement with operating cash flow of $13.3B. Capital expenditure patterns show irregular timing.',
            storagePath: '/uploads/2024/12/Tesla_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'TSLA_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Q1 report with automotive gross margin of 18.5%. Vehicle deliveries of 422,875 units up 36% YoY.',
            storagePath: '/uploads/2024/09/TSLA_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Tesla_Annual_Report_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Comprehensive annual report detailing Cybertruck production ramp and Full Self-Driving software improvements.',
            storagePath: '/uploads/2024/12/Tesla_Annual_Report_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 6 - Johnson & Johnson (7 documents)
        {
            userId: null,
            fileName: 'JNJ_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 4,
            complianceStatus: 'Pass',
            summary: 'Annual report with sales of $85.2B across pharmaceutical, medical devices, and consumer health segments. Legal reserves show normal provisions.',
            storagePath: '/uploads/2024/12/JNJ_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JohnsonAndJohnson_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Q3 report with pharmaceutical sales of $13.9B, up 4.3% operationally. Strong performance in immunology and oncology.',
            storagePath: '/uploads/2024/11/JohnsonAndJohnson_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JohnsonAndJohnson_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'failed',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/11/JohnsonAndJohnson_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JNJ_10Q_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/12/JNJ_10Q_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JohnsonAndJohnson_Income_Statement_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 5,
            complianceStatus: 'Review',
            summary: 'Q2 income statement with sales of $22.4B. Some inventory valuation methods across international subsidiaries need standardization.',
            storagePath: '/uploads/2024/10/JohnsonAndJohnson_Income_Statement_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JohnsonAndJohnson_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Cash flow statement showing operating cash flow of $20.8B with dividend payments of $11.7B to shareholders.',
            storagePath: '/uploads/2024/11/JohnsonAndJohnson_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'JNJ_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 0,
            complianceStatus: 'Pass',
            summary: 'Q1 quarterly filing with adjusted operational sales growth of 5.6%. Medical devices sales reached $7.2B.',
            storagePath: '/uploads/2024/09/JNJ_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 7 - ExxonMobil (8 documents)
        {
            userId: null,
            fileName: 'XOM_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'high',
            anomalyCount: 12,
            complianceStatus: 'Failed',
            summary: 'Annual report with revenue of $344.6B. Critical issues found in proved reserves estimation and environmental liability accruals.',
            storagePath: '/uploads/2024/12/XOM_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'ExxonMobil_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 7,
            complianceStatus: 'Review',
            summary: 'Q2 report with earnings of $9.2B. Unusual patterns in commodity hedging valuations and derivative positions.',
            storagePath: '/uploads/2024/10/ExxonMobil_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'ExxonMobil_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Balance sheet with total assets of $376.3B including property, plant and equipment of $215.8B.',
            storagePath: '/uploads/2024/11/ExxonMobil_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'XOM_10Q_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/11/XOM_10Q_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'ExxonMobil_Income_Statement_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 6,
            complianceStatus: 'Review',
            summary: 'Q4 income statement with net income of $7.6B. Refining margins and inventory cost flow assumptions need clarification.',
            storagePath: '/uploads/2024/12/ExxonMobil_Income_Statement_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'ExxonMobil_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Annual cash flow with operating cash flow of $55.4B and capital expenditures of $23.1B for upstream development.',
            storagePath: '/uploads/2024/12/ExxonMobil_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'XOM_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Q1 report with earnings of $8.2B driven by higher production volumes and improved downstream margins.',
            storagePath: '/uploads/2024/09/XOM_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'ExxonMobil_Annual_Report_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'failed',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/12/ExxonMobil_Annual_Report_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 8 - Walmart (7 documents)
        {
            userId: null,
            fileName: 'WMT_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Annual report with total revenue of $648.1B and net sales growth of 6.0%. E-commerce sales grew 24% with strong omnichannel integration.',
            storagePath: '/uploads/2024/12/WMT_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Walmart_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 4,
            complianceStatus: 'Pass',
            summary: 'Q4 quarterly report with revenue of $173.4B. Minor discrepancies in inventory shrinkage rates across store formats.',
            storagePath: '/uploads/2024/12/Walmart_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Walmart_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/11/Walmart_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'WMT_10Q_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Q2 filing with consolidated net sales of $161.6B, up 4.8%. Walmart+ membership continues strong momentum.',
            storagePath: '/uploads/2024/10/WMT_10Q_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Walmart_Income_Statement_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 5,
            complianceStatus: 'Review',
            summary: 'Q3 income statement with operating income of $6.7B. Some allocation differences in distribution center costs.',
            storagePath: '/uploads/2024/11/Walmart_Income_Statement_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Walmart_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Cash flow statement showing operating cash flow of $36.1B with free cash flow of $24.8B after capital investments.',
            storagePath: '/uploads/2024/12/Walmart_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'WMT_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Q1 report with comp sales up 3.8% in U.S. and 7.2% at Sam\'s Club. International segment delivered solid performance.',
            storagePath: '/uploads/2024/09/WMT_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 9 - Amazon (8 documents)
        {
            userId: null,
            fileName: 'AMZN_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 6,
            complianceStatus: 'Review',
            summary: 'Annual report with net sales of $574.8B. AWS revenue of $90.8B with operating income of $24.6B. Some capitalized software development cost patterns need review.',
            storagePath: '/uploads/2024/12/AMZN_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Amazon_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'high',
            anomalyCount: 10,
            complianceStatus: 'Failed',
            summary: 'Q3 quarterly report with net sales of $158.9B. Significant anomalies in fulfillment center asset depreciation and third-party seller fee recognition.',
            storagePath: '/uploads/2024/11/Amazon_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Amazon_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Balance sheet showing total assets of $527.9B with cash and marketable securities of $88.1B.',
            storagePath: '/uploads/2024/11/Amazon_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'AMZN_10Q_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/12/AMZN_10Q_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Amazon_Income_Statement_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 5,
            complianceStatus: 'Review',
            summary: 'Q2 income statement with operating income of $14.7B. Stock-based compensation allocation across segments requires verification.',
            storagePath: '/uploads/2024/10/Amazon_Income_Statement_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Amazon_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'failed',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/12/Amazon_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'AMZN_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Q1 report with net sales of $143.3B, up 13% YoY. Prime membership remains robust with improved retention rates.',
            storagePath: '/uploads/2024/09/AMZN_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Amazon_Annual_Report_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Comprehensive annual report highlighting advertising services growth of 24% and continued AWS market leadership.',
            storagePath: '/uploads/2024/12/Amazon_Annual_Report_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 10 - Meta (7 documents)
        {
            userId: null,
            fileName: 'META_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 7,
            complianceStatus: 'Review',
            summary: 'Annual report with revenue of $134.9B from advertising. Reality Labs losses of $16.1B raise questions about asset impairment testing.',
            storagePath: '/uploads/2024/12/META_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Meta_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Q2 quarterly filing with revenue of $39.1B, up 22% YoY. Daily active people reached 3.27B across family of apps.',
            storagePath: '/uploads/2024/10/Meta_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Meta_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/11/Meta_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'META_10Q_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'high',
            anomalyCount: 11,
            complianceStatus: 'Failed',
            summary: 'Q3 report with revenue of $40.6B. Critical issues in deferred tax asset valuation and unusual patterns in legal accruals.',
            storagePath: '/uploads/2024/11/META_10Q_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Meta_Income_Statement_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 4,
            complianceStatus: 'Pass',
            summary: 'Q4 income statement with net income of $14.0B. Content moderation and infrastructure costs show expected seasonal patterns.',
            storagePath: '/uploads/2024/12/Meta_Income_Statement_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Meta_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Annual cash flow with operating cash flow of $71.1B and capital expenditures of $28.1B for data center expansion.',
            storagePath: '/uploads/2024/12/Meta_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'META_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Q1 filing with revenue of $36.5B. Ad impressions increased 20% with average price per ad up 6%.',
            storagePath: '/uploads/2024/09/META_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 11 - Siemens (8 documents)
        {
            userId: null,
            fileName: 'SIE_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Annual report with revenue of €77.8B across digital industries, smart infrastructure, and mobility. Orders up 7% to €87.7B.',
            storagePath: '/uploads/2024/12/SIE_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Siemens_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 6,
            complianceStatus: 'Review',
            summary: 'Q4 quarterly report with revenue of €20.3B. Some foreign currency translation adjustments and hedging positions need further analysis.',
            storagePath: '/uploads/2024/12/Siemens_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Siemens_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'failed',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/11/Siemens_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'SIE_10Q_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/10/SIE_10Q_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Siemens_Income_Statement_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Q3 income statement with industrial business profit of €3.8B. Digital Industries margin improved to 22.1%.',
            storagePath: '/uploads/2024/11/Siemens_Income_Statement_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Siemens_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 5,
            complianceStatus: 'Review',
            summary: 'Cash flow statement with free cash flow of €7.2B. Working capital movements across regions show some timing differences.',
            storagePath: '/uploads/2024/12/Siemens_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'SIE_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Q1 report with orders of €21.9B. Strong automation business performance with book-to-bill ratio of 1.13.',
            storagePath: '/uploads/2024/09/SIE_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Siemens_Annual_Report_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Comprehensive annual report highlighting sustainability initiatives and smart infrastructure growth of 11% organically.',
            storagePath: '/uploads/2024/12/Siemens_Annual_Report_2024.pdf',
            createdAt: getRandomDate(60),
        },

        // Company 12 - Toyota (7 documents)
        {
            userId: null,
            fileName: 'TM_10K_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 5,
            complianceStatus: 'Pass',
            summary: 'Annual report with consolidated revenue of ¥45.1T. Global sales of 10.3M vehicles with some warranty reserve estimation complexities.',
            storagePath: '/uploads/2024/12/TM_10K_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Toyota_Q3_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'high',
            anomalyCount: 9,
            complianceStatus: 'Failed',
            summary: 'Q3 report with revenue of ¥11.4T. Significant anomalies in inventory valuation methods across different markets and unusual currency hedge accounting.',
            storagePath: '/uploads/2024/11/Toyota_Q3_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Toyota_Balance_Sheet_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'processing',
            riskLevel: null,
            anomalyCount: 0,
            complianceStatus: null,
            summary: null,
            storagePath: '/uploads/2024/11/Toyota_Balance_Sheet_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'TM_10Q_Q4_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 1,
            complianceStatus: 'Pass',
            summary: 'Q4 filing with operating income of ¥1.2T. Hybrid vehicle sales reached record levels with strong RAV4 and Camry demand.',
            storagePath: '/uploads/2024/12/TM_10Q_Q4_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Toyota_Income_Statement_Q2_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'medium',
            anomalyCount: 4,
            complianceStatus: 'Review',
            summary: 'Q2 income statement with net income of ¥1.3T. R&D capitalization policies for electric vehicle development need standardization.',
            storagePath: '/uploads/2024/10/Toyota_Income_Statement_Q2_2024.pdf',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'Toyota_Cash_Flow_2024.xlsx',
            fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 2,
            complianceStatus: 'Pass',
            summary: 'Annual cash flow with operating activities generating ¥5.7T and strategic investments in battery technology totaling ¥1.5T.',
            storagePath: '/uploads/2024/12/Toyota_Cash_Flow_2024.xlsx',
            createdAt: getRandomDate(60),
        },
        {
            userId: null,
            fileName: 'TM_10Q_Q1_2024.pdf',
            fileType: 'application/pdf',
            fileSize: getRandomFileSize(),
            uploadDate: getRandomDate(60),
            status: 'completed',
            riskLevel: 'low',
            anomalyCount: 3,
            complianceStatus: 'Pass',
            summary: 'Q1 report with consolidated sales of 2.4M vehicles. North American operations showed robust performance with 8% growth.',
            storagePath: '/uploads/2024/09/TM_10Q_Q1_2024.pdf',
            createdAt: getRandomDate(60),
        },
    ];

    await db.insert(documents).values(sampleDocuments);
    
    console.log('✅ Documents seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});