import { db } from '@/db';
import { notifications } from '@/db/schema';

async function main() {
    const now = new Date();
    const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    
    const getRandomDate = (start: Date, end: Date) => {
        return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
    };

    const getRandomDocumentId = () => Math.floor(Math.random() * 90) + 1;
    const getRandomAlertId = () => Math.floor(Math.random() * 120) + 1;

    const sampleNotifications = [
        // EMAIL notifications (26 total - 40%)
        {
            userId: null,
            channel: 'email',
            type: 'alert',
            title: 'Critical Alert: Debt-to-Equity Ratio Exceeded',
            message: 'Critical Alert: Debt-to-Equity ratio exceeded threshold for Tesla Inc. Current ratio: 2.8 vs threshold: 2.0. Immediate review recommended for risk assessment.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 45000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'report_ready',
            title: 'Report Ready: Q4 2024 Audit Summary',
            message: 'Report Ready: Q4 2024 Audit Summary for JPMorgan Chase is now available. The comprehensive analysis includes risk assessment, compliance checks, and financial metrics evaluation.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 78000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'analysis_complete',
            title: 'Analysis Complete: Apple 10-K Processing Done',
            message: 'Analysis Complete: Document "Apple_10K_2024.pdf" processed successfully. Extracted 124 financial metrics, identified 3 key findings, and completed compliance verification.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 92000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'threshold_breach',
            title: 'Threshold Breach: Cash Flow Alert',
            message: 'Threshold Breach: Cash flow turned negative for ExxonMobil in Q3 2024. Operating cash flow: -$245M vs expected positive flow. Liquidity concerns require attention.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 15000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'alert',
            title: 'High Severity: Fraud Pattern Detected',
            message: 'High Severity: Fraud pattern detected in Document "JPM_10K_2024.pdf". Identified inconsistencies in revenue recognition and unusual expense patterns. Confidence score: 87%.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 28000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'report_ready',
            title: 'Generated Report: IFRS Compliance Analysis',
            message: 'Generated Report: IFRS Compliance Analysis - Microsoft Corporation is complete. The report covers Q1-Q4 2024 financial statements with detailed compliance verification.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 105000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'analysis_complete',
            title: 'Document Analysis Finished: Tesla 10-Q',
            message: 'Document Analysis Finished: 8 anomalies detected in Tesla 10-Q filing. Key issues include unusual inventory valuation changes and revenue timing discrepancies.',
            status: 'pending',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'threshold_breach',
            title: 'Critical: Current Ratio Below Minimum',
            message: 'Critical: Current ratio dropped below 1.0 for Company X, now at 0.87. This indicates potential short-term liquidity issues and working capital constraints.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 34000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'alert',
            title: 'Risk Alert: Liquidity Ratio Warning',
            message: 'Risk Alert: Liquidity ratio below minimum for Goldman Sachs. Current quick ratio: 0.92 vs minimum threshold: 1.0. Recommend immediate working capital assessment.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 67000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'report_ready',
            title: 'Investor Memo Complete: Apple Q3 2024',
            message: 'Investor Memo Complete: Apple Inc. Q3 2024 Financial Analysis ready for review. Includes comprehensive performance metrics, market position analysis, and risk factors.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 89000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'analysis_complete',
            title: 'Compliance Check Done: Microsoft Q2 2024',
            message: 'Compliance Check Done: Microsoft Q2 2024 - 2 violations found. Issues identified: Revenue recognition timing and disclosure adequacy. Detailed report available.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 56000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'threshold_breach',
            title: 'Warning: ROE Below Industry Benchmark',
            message: 'Warning: ROE fell below 8% industry benchmark for retail sector company. Current ROE: 6.4% indicates declining profitability and operational efficiency concerns.',
            status: 'failed',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'alert',
            title: 'Medium Alert: Unusual Expense Pattern',
            message: 'Medium Alert: Unusual expense pattern detected in Q4 financial statements. Operating expenses increased 34% quarter-over-quarter without corresponding revenue growth.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 42000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'report_ready',
            title: 'Risk Assessment Report: Banking Sector',
            message: 'Risk Assessment Report: Banking Sector Q4 2024 is now available. Comprehensive analysis of 15 major banks including stress testing results and regulatory compliance status.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 98000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'analysis_complete',
            title: 'Financial Metrics Extracted: Amazon 10-K',
            message: 'Financial Metrics Extracted: Successfully processed Amazon 10-K 2024 filing. Extracted 156 metrics including revenue breakdown by segment, operating margins, and cash flow analysis.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 73000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'alert',
            title: 'Critical: Debt Covenant Violation Risk',
            message: 'Critical: Debt Covenant Violation Risk identified for retail company. Interest coverage ratio: 1.8x vs covenant requirement: 2.5x. Immediate remediation planning required.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 19000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'report_ready',
            title: 'Quarterly Performance Summary Ready',
            message: 'Quarterly Performance Summary Ready: Tech sector analysis covering FAANG companies. Includes comparative metrics, growth trends, and valuation analysis for Q3 2024.',
            status: 'pending',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'threshold_breach',
            title: 'Alert: Inventory Turnover Decline',
            message: 'Alert: Inventory turnover declined significantly for manufacturing company. Current ratio: 3.2x vs historical average: 6.8x. Indicates potential obsolescence or demand issues.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 51000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'analysis_complete',
            title: 'Benchmark Analysis Complete: Industry Comparison',
            message: 'Benchmark Analysis Complete: Industry Comparison processed for automotive sector. Compared 12 companies across 45 financial metrics with peer group analysis.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 110000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'alert',
            title: 'Revenue Recognition Anomaly Detected',
            message: 'Revenue Recognition Anomaly Detected in pharmaceutical company filing. Unusual revenue timing patterns identified with 78% confidence. Multiple contracts show premature recognition.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 36000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'report_ready',
            title: 'ESG Compliance Report Generated',
            message: 'ESG Compliance Report Generated: Annual sustainability assessment for Fortune 500 company complete. Covers environmental metrics, social impact, and governance practices.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 87000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'analysis_complete',
            title: 'Cross-Document Analysis Finished',
            message: 'Cross-Document Analysis Finished: Analyzed 5 consecutive quarterly reports for trend identification. Detected 3 emerging patterns and 2 potential red flags requiring attention.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 94000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'alert',
            title: 'Working Capital Warning',
            message: 'Working Capital Warning: Negative working capital trend detected over past 3 quarters. Current working capital: -$45M and declining. Cash conversion cycle increasing significantly.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 62000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'report_ready',
            title: 'Audit Trail Report: Document Changes',
            message: 'Audit Trail Report: Document Changes summary for fiscal year 2024 is ready. Tracked 234 document modifications across 67 filings with detailed change attribution.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 76000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'threshold_breach',
            title: 'Operating Margin Below Target',
            message: 'Operating Margin Below Target: Margin compressed to 8.2% vs target 12%. Cost pressures and pricing challenges impacting profitability. Margin recovery plan needed.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 48000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'email',
            type: 'analysis_complete',
            title: 'Sentiment Analysis Complete: MD&A Section',
            message: 'Sentiment Analysis Complete: MD&A Section processing done for annual report. Overall tone: cautiously optimistic. Identified 12 forward-looking statements and 5 risk disclosures.',
            status: 'pending',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },

        // SMS notifications (13 total - 20%)
        {
            userId: null,
            channel: 'sms',
            type: 'alert',
            title: 'URGENT: Credit Rating Downgrade Alert',
            message: 'URGENT: Credit Rating Downgrade Alert for major financial institution. Rating dropped from A to BBB+ due to capital adequacy concerns. Immediate portfolio review recommended.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 8000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'report_ready',
            title: 'Flash Report: Market Event Analysis',
            message: 'Flash Report: Market Event Analysis ready. Covers impact of recent economic data release on portfolio companies. Includes immediate action items and risk mitigation strategies.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 12000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'analysis_complete',
            title: 'Priority Document Processed',
            message: 'Priority Document Processed: Earnings call transcript analysis complete for Tesla. Identified 4 key business updates and 2 material risks. Sentiment: mixed with caution.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 23000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'threshold_breach',
            title: 'CRITICAL: Leverage Ratio Exceeded',
            message: 'CRITICAL: Leverage Ratio Exceeded maximum threshold for energy company. Net debt to EBITDA: 5.8x vs limit: 4.5x. Covenant violation risk high. Action required immediately.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 6000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'alert',
            title: 'Material Restatement Filed',
            message: 'Material Restatement Filed: Public company filed 10-K/A restating prior year financials. Revenue adjustment: -$78M. Fraud indicators detected with 92% confidence score.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 11000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'report_ready',
            title: 'Daily Risk Dashboard Updated',
            message: 'Daily Risk Dashboard Updated: Morning risk summary ready for review. Portfolio risk score: 6.8/10 (up from 5.2). Three companies flagged for increased monitoring.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 18000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'analysis_complete',
            title: 'Real-time Analysis: Breaking News',
            message: 'Real-time Analysis: Breaking News - Major acquisition announced. Analyzed press release and preliminary financials. Strategic fit: positive. Integration risk: moderate to high.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 14000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'threshold_breach',
            title: 'Cash Position Alert',
            message: 'Cash Position Alert: Cash and equivalents dropped below $100M threshold for mid-cap company. Burn rate accelerating. Liquidity runway: estimated 8 months at current rate.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 9000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'alert',
            title: 'Going Concern Warning',
            message: 'Going Concern Warning: Auditor added going concern qualification to annual report. Company facing significant liquidity challenges and covenant breach. High risk situation.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 7000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'report_ready',
            title: 'Executive Summary: Portfolio Review',
            message: 'Executive Summary: Portfolio Review complete. Top 3 risks identified. 2 companies require immediate attention. Detailed action plan ready for management review.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 21000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'analysis_complete',
            title: 'Competitive Analysis Done',
            message: 'Competitive Analysis Done: Processed 8-K filings from 5 competitors. Key finding: Industry margin pressure increasing. Market share shifts detected. Strategic implications significant.',
            status: 'failed',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'alert',
            title: 'Insider Trading Activity Spike',
            message: 'Insider Trading Activity Spike: Detected unusual insider selling pattern at tech company. 5 executives sold shares worth $45M total over past 2 weeks. Pattern analysis: concerning.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 16000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'sms',
            type: 'threshold_breach',
            title: 'Gross Margin Compression Alert',
            message: 'Gross Margin Compression Alert: Margin fell to 28.4% from 35.2% year-over-year. Input cost inflation and competitive pricing pressure impacting profitability significantly.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 13000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },

        // PUSH notifications (16 total - 25%)
        {
            userId: null,
            channel: 'push',
            type: 'alert',
            title: 'Document Upload Complete',
            message: 'Document Upload Complete: Your 10-K filing for FY2024 has been successfully uploaded and validated. Automated analysis will begin shortly. Expected completion: 15 minutes.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 5000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'report_ready',
            title: 'Weekly Digest Available',
            message: 'Weekly Digest Available: Your personalized financial analysis digest for week ending Dec 15 is ready. Covers 12 document analyses and 8 key alerts from your watchlist.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 25000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'analysis_complete',
            title: 'Financial Ratios Calculated',
            message: 'Financial Ratios Calculated: Completed comprehensive ratio analysis for quarterly filing. Generated 45 key ratios with peer comparisons and historical trending.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 31000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'threshold_breach',
            title: 'Watchlist Alert Triggered',
            message: 'Watchlist Alert Triggered: One of your monitored companies breached debt covenant threshold. Review alert #4567 for details and recommended actions.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 10000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'alert',
            title: 'New Document Available for Review',
            message: 'New Document Available for Review: Competitor filed amended 10-K with material changes. Changes detected in revenue recognition section and risk factors. Review recommended.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 22000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'report_ready',
            title: 'Custom Report Generated',
            message: 'Custom Report Generated: Your requested peer analysis comparing tech sector companies is complete. Includes metrics comparison, valuation analysis, and growth projections.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 54000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'analysis_complete',
            title: 'AI Analysis Results Ready',
            message: 'AI Analysis Results Ready: Machine learning model completed analysis of quarterly trends. Identified 3 emerging patterns and 2 anomalies requiring attention. Confidence: high.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 37000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'alert',
            title: 'Scheduled Analysis Starting',
            message: 'Scheduled Analysis Starting: Your daily automated analysis routine is beginning. Processing 15 documents from your portfolio. Estimated completion time: 25 minutes.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 20000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'report_ready',
            title: 'Compliance Dashboard Updated',
            message: 'Compliance Dashboard Updated: Latest regulatory compliance status for all monitored entities. 3 items require attention. Overall compliance score: 94/100.',
            status: 'pending',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'analysis_complete',
            title: 'Version Comparison Complete',
            message: 'Version Comparison Complete: Analyzed differences between current and prior version of annual report. Found 23 substantive changes including 5 in financial statements.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 44000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'threshold_breach',
            title: 'Performance Metric Alert',
            message: 'Performance Metric Alert: Revenue growth rate fell below 10% target for consecutive quarters. Current growth: 7.2%. Trend analysis suggests continued deceleration.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 17000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'alert',
            title: 'Knowledge Graph Updated',
            message: 'Knowledge Graph Updated: Added 45 new entities and 78 relationships from recent document analysis. Enhanced insights now available for network analysis queries.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 33000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'report_ready',
            title: 'Forecast Model Results',
            message: 'Forecast Model Results: Updated financial projections for next 4 quarters available. Model confidence: 82%. Key drivers: revenue growth and margin expansion.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 61000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'analysis_complete',
            title: 'Natural Language Query Processed',
            message: 'Natural Language Query Processed: Your question about industry trends has been answered. Found 12 relevant documents and generated comprehensive response with citations.',
            status: 'pending',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'alert',
            title: 'System Maintenance Scheduled',
            message: 'System Maintenance Scheduled: Platform upgrade scheduled for tonight 11 PM - 2 AM EST. Document processing will be temporarily unavailable. All data secure.',
            status: 'sent',
            documentId: null,
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 27000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'push',
            type: 'threshold_breach',
            title: 'Budget Variance Alert',
            message: 'Budget Variance Alert: Analysis costs exceeded monthly budget threshold by 15%. Current usage: $1,725 vs budget: $1,500. Consider reviewing usage patterns.',
            status: 'sent',
            documentId: null,
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 39000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },

        // SLACK notifications (10 total - 15%)
        {
            userId: null,
            channel: 'slack',
            type: 'alert',
            title: 'Team Alert: Critical Finding',
            message: 'Team Alert: Critical Finding discovered in portfolio company analysis. Material weakness in internal controls identified. @finance-team please review urgently.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 15000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'report_ready',
            title: 'Morning Briefing Ready',
            message: 'Morning Briefing Ready: Daily financial markets and portfolio summary prepared. Key highlights: 3 earnings releases, 2 regulatory filings, 1 rating change.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 29000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'analysis_complete',
            title: 'Batch Processing Complete',
            message: 'Batch Processing Complete: Overnight analysis of 47 documents finished successfully. Results available in dashboard. 4 items flagged for team review.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 68000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'threshold_breach',
            title: 'Portfolio Risk Threshold Exceeded',
            message: 'Portfolio Risk Threshold Exceeded: Overall portfolio risk score increased to 7.8/10 from 6.2/10. Primary drivers: market volatility and credit rating changes.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 11000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'alert',
            title: 'Collaboration Request',
            message: 'Collaboration Request: @analyst-team document review needed for complex restructuring case. Multiple scenarios analyzed. Team input requested on risk assessment.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 24000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'report_ready',
            title: 'Monthly Performance Report',
            message: 'Monthly Performance Report: November 2024 portfolio analysis complete. Processed 234 documents. Overall performance: stable. 2 positions flagged for potential action.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 82000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'analysis_complete',
            title: 'Industry Research Complete',
            message: 'Industry Research Complete: Comprehensive sector analysis finished. Analyzed 89 companies across healthcare sector. Key trends identified. Report shared in #research channel.',
            status: 'pending',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'alert',
            title: 'Workflow Approval Needed',
            message: 'Workflow Approval Needed: Automated analysis detected high-risk scenario requiring management approval before proceeding. @risk-committee please review case #892.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: getRandomAlertId(),
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 19000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'report_ready',
            title: 'Audit Committee Package Ready',
            message: 'Audit Committee Package Ready: Quarterly board materials prepared. Includes executive summary, detailed findings, and management recommendations. Shared in #audit-committee.',
            status: 'sent',
            documentId: getRandomDocumentId(),
            alertId: null,
            sentAt: new Date(getRandomDate(thirtyDaysAgo, now).getTime() + 95000).toISOString(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
        {
            userId: null,
            channel: 'slack',
            type: 'threshold_breach',
            title: 'Team Utilization Alert',
            message: 'Team Utilization Alert: Document analysis queue backlog exceeded 100 items. Current queue: 127 documents. Consider resource allocation adjustment or prioritization.',
            status: 'failed',
            documentId: null,
            alertId: getRandomAlertId(),
            sentAt: null,
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
        },
    ];

    await db.insert(notifications).values(sampleNotifications);
    
    console.log('✅ Notifications seeder completed successfully - 65 records created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});